### PR TITLE
push to stable

### PR DESCRIPTION
**Pull request by vanhauser-thc**

### CODE REVIEW

**Comment by SonicStark** [comment]
Currently the CI workflow failed, since `afl-cc` didn't work properly when do linking. I opened #1968 which should fix current messes.

**Comment by SonicStark** [comment]
FYI: I have found some SEGV errors when `afl-cc` parsing response files. I'll open a PR for the patch in the next few days.

**Comment by vanhauser-thc** [comment]
> FYI: I have found some SEGV errors when `afl-cc` parsing response files. I'll open a PR for the patch in the next few days.

I will wait for your PR until I merge this. thank you.

**Comment by vanhauser-thc** [comment]
> FYI: I have found some SEGV errors when `afl-cc` parsing response files. I'll open a PR for the patch in the next few days.

When will you be able to send the pr?

**Comment by SonicStark** [comment]
> > FYI: I have found some SEGV errors when `afl-cc` parsing response files. I'll open a PR for the patch in the next few days.
> 
> When will you be able to send the pr?

Before Jan 31, 2024, 18:00 (UTC). 
I've completed new implementation of parsing response file, locally. And currently I'm using AFL++ to fuzz this part, and make some other regression tests with `libiberty` and `libclang`, as benchmark. BTW, file parsing is really a buggy work🤣
Comments in `afl-cc.c` are also on the way.

**Comment by vanhauser-thc** [comment]
Thanks! The response file support was a hack to support a specific target…

**Pull request merged**
