### PR TITLE
add docs for build on MacOS m1

### PR DESCRIPTION
**Pull request by Windforce17**
Test on macOS 12.1. Also support `afl-clang-fast`

### CODE REVIEW

**Comment by vanhauser-thc** [comment]
for me brew installs clang/llvm-config etc. here `/usr/local/Cellar/llvm/13.0.0_2/bin` and `/opt/local/libexec/llvm-devel/bin`
why is that different on your platform?

**Comment by vanhauser-thc** [comment]
@Windforce17 please get back to me. I need that question answered :)

**Comment by Windforce17** [comment]
> for me brew installs clang/llvm-config etc. here `/usr/local/Cellar/llvm/13.0.0_2/bin` and `/opt/local/libexec/llvm-devel/bin` why is that different on your platform?

M1 max macOS 12.1.
This is  `brew info llvm` output
```
To use the bundled libc++ please add the following LDFLAGS:
  LDFLAGS="-L/opt/homebrew/opt/llvm/lib -Wl,-rpath,/opt/homebrew/opt/llvm/lib"

llvm is keg-only, which means it was not symlinked into /opt/homebrew,
because macOS already provides this software and installing another version in
parallel can cause all kinds of trouble.

If you need to have llvm first in your PATH, run:
  echo 'export PATH="/opt/homebrew/opt/llvm/bin:$PATH"' >> ~/.zshrc

For compilers to find llvm you may need to set:
  export LDFLAGS="-L/opt/homebrew/opt/llvm/lib"
  export CPPFLAGS="-I/opt/homebrew/opt/llvm/include"
```

**Comment by vanhauser-thc** [comment]
I changed it as it differs on brew/macos: 861bd5e04b5030b3fc345c1022c46e92eb52a312
dont worry, you will get your tshirt ;)

**Comment by llzmb** [comment]
Hi @Windforce17,

thank you for your contribution to the AFL++ docs! You won one of the very rare AFL++ t-shirts (see https://twitter.com/aflplusplus/status/1480836318175408138)!

Please e-mail @vanhauser-thc (mh@mh-sec.de) your address, size, and style (straight or fitted) until this upcoming Friday, January 21st, 2022.

Congrats! 🥳

**Pull request closed without merging**
