### PR TITLE
Autodict-QL : Token generation for fuzzing with CodeQL

### PR DESCRIPTION
**Pull request by Microsvuln**
Hey guys.

This is the initial PR for Autodict-QL, a token generation plugin for AFL++ with using the power of CodeQL semantic analysis engine.  (Somehow integrating CodeQL usability to AFL++ :-) )

For now, there are 5 codeql scripts that extracts tokens from the CodeBase and use them as dictionaries for fuzzing. additional scripts can also be added and the integration is so easy .

Please let me know your comments :-)

Thanks
Arash

### CODE REVIEW

**Comment by vanhauser-thc** [comment]
looks good to me, thank you!

**Comment by DuckRui** [comment]
Hello, I have a question about Autodict-QL.I used it  generates some tokens. Do I must let AFL++ fuzzing in deterministic(set -D ), if I want these tokens usdful? Beacuse I see havoc stage will also use tokens to replace or insert. I want to know whether deterministic stage is must?

**Comment by vanhauser-thc** [comment]
you do not need -D, havoc uses all mutation strategies.

**Comment by DuckRui** [comment]
> you do not need -D, havoc uses all mutation strategies.

I get it. Thank you very much!

**Pull request merged**
