### PR TITLE
Remove self-referential symlink

### PR DESCRIPTION
**Pull request by frewsxcv**
Hi. I maintain the [Rust bindings for AFL](https://github.com/rust-fuzz/afl.rs) which vendors the AFLplusplus project. Upon packaging for release, Cargo (the Rust build/package tool) hits an error because it tries to resolve all symlinks:

```
error: failed to prepare local package for uploading

Caused by:
  failed to open for archiving: `/Users/coreyf/dev/rust-fuzz/afl.rs/AFLplusplus/custom_mutators/honggfuzz/libhfcommon/libhfcommon/libhfcommon/libhfcommon/libhfcommon/libhfcommon/libhfcommon/libhfcommon/libhfcommon/libhfcommon/libhfcommon/libhfcommon/libhfcommon/libhfcommon/libhfcommon/libhfcommon/libhfcommon/libhfcommon/libhfcommon/libhfcommon/libhfcommon/libhfcommon/libhfcommon/libhfcommon/libhfcommon/libhfcommon/libhfcommon/libhfcommon/libhfcommon/libhfcommon/libhfcommon/libhfcommon/libhfcommon`

Caused by:
  Too many levels of symbolic links (os error 62)
```

In particular, `custom_mutators/honggfuzz/libhfcommon` references its own directory `custom_mutators/honggfuzz`, and we hit a recursive issue. Would it be okay to remove this symlink altogether?

### CODE REVIEW

**Comment by andreafioraldi** [comment]
lgtm

**Review by andreafioraldi — APPROVED** [review]

**Comment by andreafioraldi** [comment]
merging to dev, as we don't accept PRs to stable.
You can reference the commit id in afl.rs and release now, or wait for a push to stable.

**Comment by vanhauser-thc** [comment]
does not look good to me :)
the paths are from honggfuzz and the change will be overwritten on next sync.
the symlinks are not self referential. dunno where this comes from, but looks fine on my checkout:

```
-rw-r--r-- 1 root root    43 Feb 18 11:14 common.h
lrwxrwxrwx 1 root root     1 Feb  5 10:42 libhfcommon -> .
lrwxrwxrwx 1 root root     8 Feb  5 10:42 log.h -> common.h
lrwxrwxrwx 1 root root     8 Feb  5 10:42 util.h -> common.h
[...]
```
I dont see anything problematic.

**Comment by frewsxcv** [comment]
@vanhauser-thc Do you know why `libhfcommon` references the directory it's in?

**Comment by frewsxcv** [comment]
To clarify, this is the problematic symlink in question:

```
lrwxrwxrwx 1 root root     1 Feb  5 10:42 libhfcommon -> .
```

**Comment by andreafioraldi** [comment]
@vanhauser-thc auto sync with hongfuzz is broken is any case, i had to fix it by hand

**Comment by andreafioraldi** [comment]
i'll try to push a better hack asap, at least now he can release doing a checkout to the commit

**Comment by vanhauser-thc** [comment]
@frewsxcv IMHO it is not the link that is broken - the link is fine. is is rather the feature that you / the project is using that follows them. find etc. other commands have no problem with it. and symlink to the current directory is a common thing.

**Comment by vanhauser-thc** [comment]
> @vanhauser-thc auto sync with hongfuzz is broken is any case, i had to fix it by hand

what is broken for you? I updated it yesterday and it worked just fine.

**Comment by andreafioraldi** [comment]
> what is broken for you? I updated it yesterday and it worked just fine.

Yes Robert changed an API, see https://github.com/AFLplusplus/AFLplusplus/commit/4290cb587763b334c7fb1213bc50dada8d62765d

**Comment by andreafioraldi** [comment]
> @frewsxcv IMHO it is not the link that is broken - the link is fine. is is rather the feature that you / the project is using that follows them. find etc. other commands have no problem with it. and symlink to the current directory is a common thing.

It is cargo that follows links to create packages for crates.io (PyPI for Rust). Cannot be avoided, I'll try to find a solution that avoid symlinks without touching mangle.c

**Comment by andreafioraldi** [comment]
https://github.com/AFLplusplus/AFLplusplus/commit/17211253b2298958dfbd9dae79acf96a4d9ca32d does it

**Comment by vanhauser-thc** [comment]
looks good!

**Pull request merged**
