### PR TITLE
Fixes/optimin

### PR DESCRIPTION
**Pull request by adrianherrera**
Hey again AFL++ devs!

Following our conversations on Twitter, I've made some improvements to the optimin corpus minimizer. This includes:

* Add support for all afl-cmin command-line arguments and environment variables
* Make use of afl-showmap forkserver
* Add target binary test (same as cmin does)
* Other misc. fixes and refactoring

Let me know what you think!

### CODE REVIEW

**Comment by vanhauser-thc** [comment]
LGTM, will merge and do some tests (not sure I can do them before sunday/monday).
did you find out why optimin lost 2 edges vs. afl-cmin (see twitter message chat)?

**Comment by vanhauser-thc** [comment]
Was lucky to have kept my test commands.

```
optimin old: 3m12 runtime, 8997 edges, 583 input files
optimin new: 1m14 runtime, 8997 edges, 583 input files
```
great job, >60% faster execution time :)
compared to afl-cmin:
```
afl-cmin: 2m37 runtime, 8998 edges, 5593 input files
```
(dunno why but now showmap shows one more edge for optimin, even on the same data and same compiled binary from last test. so only one edge seems lost.)

**Comment by adrianherrera** [comment]
Hmmm that's weird, not sure what's happening with the edges.

Do you have any data that you are able to share so that I can replicate your results?

**Comment by vanhauser-thc** [comment]
sure, I put it here: https://www.mh-sec.de/data/optimin.tgz (btw you have to extract with tar xJf ... the .tgz is wrongly named by me :)

```
optimin -i seeds -o foo -- ./build/fuzz
```

ah and to obtain the coverage:
```
afl-showmap -C -i foo -o optimin.out -- ./build/fuzz
```

**Comment by adrianherrera** [comment]
No worries, will investigate over the next few days :)

**Pull request merged**
