### PR TITLE
Add automaton parser

### PR DESCRIPTION
**Pull request by yihellen**
# Add Automaton Parser to Gramatron
Right now Gramatron does not take any custom seeds because it cannot parse them to its internal automaton walk representation. Instead, it takes a place holder seed input directory and generate the initial seeds from scratch by taking a random walk on the input grammar's finite state machine. This makes Gramatron difficult to run along with other mutators.

My pull request attempts to add an automaton parser that allows Gramatron to take any input that complies with its grammar and store its automaton walk representation on the queue. 

I have added a module called `automaton_parser` to accomplish this goal. In `afl_custom_queue_new_entry`, every time a seed added to queue in Gramatron, its automaton representation (file with suffix `.aut`) would be generated if it does not exist already.

Thank you for reading my PR. Please make any suggestions that you have, I'm very eager to learn!

### CODE REVIEW

**Comment by domenukk** [comment]
Looks good to me, I'm not deep into gramatron, @andreafioraldi if you have a minute maybe take a look

**Comment by vanhauser-thc** [comment]
@yihellen can you please create another PR where you a) add the functionality to enable this or disable this feature (dunno what the default should be, enabled is fine I think?), plus add this feature description to the README of gramatron?

**Comment by vanhauser-thc** [comment]
@yihellen can you please create another PR where you a) add the functionality to enable this or disable this feature (dunno what the default should be, enabled is fine I think?), plus add this feature description to the README of gramatron?

**Comment by yihellen** [comment]
Sorry for the delayed response！
I’ll add that as soon as possible.

在 2022年6月11日，下午10:53，van Hauser ***@***.***> 写道：


think?), plus add this feature description to the README of gramatron?

**Comment by vanhauser-thc** [comment]
thanks, please dont forget.

**Comment by vanhauser-thc** [comment]
@yihellen can you please do this? otherwise I will put a hardcoded disable of this feature into the code, as we want to push to the stable branch the next days.

**Comment by yihellen** [comment]
Sorry I didn’t realize there’s a deadline here. I’m busy with some personal things recently. Feel free to ignore this PR or disable this feature altogether.

发自我的iPhone

在 2022年6月15日，下午10:38，van Hauser ***@***.***> 写道：

﻿

@yihellen<https://github.com/yihellen> can you please do this? otherwise I will put a hardcoded disable of this feature into the code, as we want to push to the stable branch the next days.

**Comment by vanhauser-thc** [comment]
yes there a few important bug fixes so we have to make a new official release, and the push to stable is the step for that.
if you can put things in until Sunday it is fine, otherwise I will put a disable in :( (we cant have a changing feature that is undocumented and not possible to disable/enable by user choice whatever the default)

**Comment by yihellen** [comment]
I don’t think I will have time to do that before Sunday. Maybe I can rebase after the new release.

发自我的iPhone

在 2022年6月16日，上午2:22，van Hauser ***@***.***> 写道：

﻿

yes there a few important bug fixes so we have to make a new official release, and the push to stable is the step for that.
if you can put things in until Sunday it is fine, otherwise I will put a disable in :( (we cant have a changing feature that is undocumented and not possible to disable/enable by user choice whatever the default)

**Comment by vanhauser-thc** [comment]
there are a few more important things I have to take care to ensure we have a good afl++ release, which might buy you another day or two.
I checked your code, and the only chance I see is to remove it as with a short glance over the code does not look like it is easy to just disable the feature easily in a central place.
so I would prefer if you can provide the changes in time, instead of me removing the changes until the stable push and then putting them back in afterwards ...

**Comment by yihellen** [comment]
So you still want me to add a flag to disable this feature?

And what’s the deadline for this change?



在 2022年6月18日，上午12:20，van Hauser ***@***.***> 写道：

﻿

there are a few more important things I have to take care to ensure we have a good afl++ release, which might buy you another day or two.
I checked your code, and the only chance I see is to remove it as with a short glance over the code does not look like it is easy to just disable the feature easily in a central place.
so I would prefer if you can provide the changes in time, instead of me removing the changes until the stable push and then putting them back in afterwards ...

**Comment by vanhauser-thc** [comment]
yes please add his. as soon as you can, if that is before we release - great, if it is later than I will remove your changes, push to stable, and then put the changes back into the dev branch.
there is one more issue I have to check before I can merge to stable and then release, so you have time until sunday or monday.

**Comment by yihellen** [comment]
okay thank you！

发自我的iPhone

在 2022年6月18日，下午12:51，van Hauser ***@***.***> 写道：

﻿

yes please add his. as soon as you can, if that is before we release - great, if it is later than I will remove your changes, push to stable, and then put the changes back into the dev branch.
there is one more issue I have to check before I can merge to stable and then release, so you have time until sunday or monday.

**Comment by vanhauser-thc** [comment]
@yihellen are you still planning to add the documentation + enable/disable feature? if so, when will it be done approximately?

**Comment by vanhauser-thc** [comment]
@yihellen is this still happening? you had over a month, it looks to me like you have no time for it :(
we have to do another release, which means for me a second time to replace your changes.
and this is work for me every time.

**Comment by yihellen** [comment]
Hi, I am so sorry but I don’t think I would have the time to finish this before today. Feel free to ignore my PR and release the stable version.

2022年6月18日 下午12:50，van Hauser ***@***.******@***.***>> 写道：



yes please add his. as soon as you can, if that is before we release - great, if it is later than I will remove your changes, push to stable, and then put the changes back into the dev branch.
there is one more issue I have to check before I can merge to stable and then release, so you have time until sunday or monday.

**Pull request merged**
