### PR TITLE
status_screen.md added

### PR DESCRIPTION
**Pull request by Alireza-Razavi**
AFL++ status screen explanations based on https://aflplus.plus/docs/status_screen with some changes in newer versions.

### CODE REVIEW

**Comment by domenukk** [comment]
It would probably make sense to link this from somewhere in the main docs, right?

**Comment by vanhauser-thc** [comment]
That information is just in a different file (during GSoD)

**Comment by Alireza-Razavi** [comment]
@domenukk @vanhauser-thc 
All docs and `md` files about the AFLplus are integrated in `docs/` and i think it makes a good sense when we can find all information about the status_screen shown by AFLplus in that directory.

**Comment by vanhauser-thc** [comment]
look into docs/afl-fuzz_approach.md - as I said it was merged into another document.
if you think that text there needs improvement - I will be happy with a PR fo rthat.

**Pull request closed without merging**
