### PR TITLE
Fix bug: compilation cannot pass when DEBUG macro is enabled

### PR DESCRIPTION
**Pull request by mark0-cn**
image

### CODE REVIEW

**Comment by domenukk** [comment]
Is this fine on Linux, MacOS and gcc and clang? IIRC the platform independent / correct way would be to use `, "%" PRId64,` here (but it's super ugly so I'd prefer `%lld` if it works fine..)

**Comment by mark0-cn** [comment]
> Is this fine on Linux, MacOS and gcc and clang? IIRC the platform independent / correct way would be to use `, "%" PRId64,` here (but it's super ugly so I'd prefer `%lld` if it works fine..)

I find this issue on MacOS and have not tried it on other platforms. But I feel like there's no problem on other platforms either. Perhaps it would be better to change to '%' PRId64?

**Comment by domenukk** [comment]
Probably safer, yes, IIRC on linux sometimes I needed `%ld` instead of `%lld` specifically, but I don't have a machine to test right now

**Comment by domenukk** [comment]
Tried it, seems fine, thanks! :)

**Comment by domenukk** [comment]
Oops actually now it warns on linux, will fix it manually

**Comment by domenukk** [comment]
Fixed in d0782a7

**Pull request merged**
