### PR TITLE
Big renaming

### PR DESCRIPTION
**Pull request by vanhauser-thc**
Please help me fix the renaming of blacklist/whitelist if anything went wrong or is not optimal.

### CODE REVIEW

**Comment by vanhauser-thc** [comment]
please fix directly and push instead of nit picking :)

**Comment by andreafioraldi** [comment]
I see a huge risk in this PR, maybe should land after the release

**Comment by andreafioraldi** [comment]
I don't see bugs, good that you didn't break backward compatibility

**Comment by vanhauser-thc** [comment]
fine with me. what is the risk though? travis is all green.

**Comment by andreafioraldi** [comment]
mmmm we did a hotfix release for last minutes features before the previous release more than one time, just saying, maybe the changes are so little that is ok

**Comment by vanhauser-thc** [comment]
we only had one bug release.
There was another time we did a short time release but that was for fixing bugs that were introduced in previous versions but important.
but yes. if it is a risk we should move it. I dont think it is one, but when we all check over the changes we get a better feeling if it is a complex change or not and then decide. we have 13 hours for that :)

**Comment by vanhauser-thc** [comment]
the change here does still process AFL_*_WHITELIST env vars, however afl-common will report it is unknown.
I am now not sure this is good. This might make people think it is not working when however it does.
I want to discourage people using the old env var so they switch, but also not break backward compatability.
opinions?

**Comment by andreafioraldi** [comment]
just show a deprecatio warning, not a not exists warning

**Comment by vanhauser-thc** [comment]
we dont have something like this yet.
should I add it?

**Pull request merged**
