### PR TITLE
Add StatsD readme

### PR DESCRIPTION
**Pull request by Edznux**
Second round of documentation PR for statsd (#684).

Let me know if something isn't clear.
@wizche : Would you mind sharing your config of your statsd_exporter for this (`statsd_mapping`) ?

_(Will do a pass of proof reading when I get some time)_

### CODE REVIEW

**Comment by vanhauser-thc** [comment]
a PNG to show how this can look like would be nice IMHO

**Comment by wizche** [comment]
Ehi @Edznux, I actually start it with default param (nothing set) and on afl++ I set `AFL_STATSD_TAGS_FLAVOR=dogstatsd`

You mean a PNG with a dashboard? Here is my dummy one
grafana1

**Comment by Edznux** [comment]
Ah, ok thanks! I can't seem to get it working without the remapping.
I added a screenshot (and it's corresponding JSON template) in the doc. Both of them are using Grafana.

Should I add the JSON template for Datadog as well ? It's the same configuration I added in my PR description (#571), here is the [gist](https://gist.github.com/Edznux/5c6fc7f2eebec96890820b17232b5d9d).

**Comment by domenukk** [comment]
This is super cool, thank you so much for your effort!

**Pull request merged**
