### PR TITLE
Haiku, fix build on x86_64

### PR DESCRIPTION
**Pull request by Begasus**

### CODE REVIEW

**Comment by vanhauser-thc** [comment]
I dont get it. if it is x86_64 then you set that it is not x86. and if it is not x86 - then it is not set ... ?

**Comment by Begasus** [comment]
I'm not the expert here, I saw our build for x86_64 failed earlier: https://build.haiku-os.org/buildmaster/master/x86_64/logviewer.html?buildruns/5611/builds/18873.log
After checking up on the source this came up and I checked a build on it that worked: https://build.haiku-os.org/buildmaster/master/x86_64/logviewer.html?buildruns/5616/builds/18878.log
This was checked on 32bit Haiku and didn't fail there, maybe someone could look into this? (the local build for x86_64 (64bit) also failed for me before this patch

**Comment by vanhauser-thc** [comment]
well what this does it disabling build checks, so no wonder it compiles then without errors :)

**Comment by Begasus** [comment]
Whoops, back to the drawing board then, I gather this can be closed :)

**Comment by vanhauser-thc** [comment]
:)

**Pull request closed without merging**
