### PR TITLE
Fix MOpt implementation flaws

### PR DESCRIPTION
**Pull request by arnow117**
Hi,

I'm reading implement of MOpt these days. It's pretty good that implementation for the MOpt such as pointer using, however I think these maybe have two flaws:

1. swarm_fitness is updated with zero if we do ```afl->temp_puppet_find = afl->total_puppet_find;``` early in pilot mode.

2. there are several missing update for ```afl->core_operator_cycles_puppet*```, which are important used in PSO update function.

I compare these logic with MOpt-AFL and make a PR, maybe we could fix this with this. 

Best wish,
arnow117

### CODE REVIEW

**Comment by arnow117** [comment]
#378

**Comment by vanhauser-thc** [comment]
good catch!
dunno what happened here. I did a direct copy-paste of the function. maybe these bugs were in originally and then later fixed in their repo.
have you checked out how this changes mutation and therefore coverage?

**Comment by arnow117** [comment]
not yet,  maybe we could run this in fuzzbench again~

**Comment by vanhauser-thc** [comment]
I did various changes in the code that improves the performance (mostly but not only) on fuzzbench a lot, it would not compare.
I can run against two targets on my system though

**Comment by arnow117** [comment]
BTW, after checking the commit history of MOpt's logic, I think maybe updating logic in core_fuzzing has been missing in when we try to do pilot&core fuzzing in mopt_common_fuzzing()

**Comment by vanhauser-thc** [comment]
ah could you do a "make code-format" please?

**Comment by arnow117** [comment]
> I did various changes in the code that improves the performance (mostly but not only) on fuzzbench a lot, it would not compare.
> I can run against two targets on my system though

Sounds great,  wish this patch is effective and thanks~

**Comment by arnow117** [comment]
> ah could you do a "make code-format" please?

oh yes I try to do it at first, but in my mac...
```
clang-format-10 is needed. Aborted.
```

**Comment by vanhauser-thc** [comment]
> > ah could you do a "make code-format" please?
> 
> oh yes I try to do it at first, but in my mac...
> 
> ```
> clang-format-10 is needed. Aborted.
> ```

ah there is the bug. Mac ;-)

**Comment by arnow117** [comment]
emm..... I just forgot add myself to README.md
please add arnow117 into it if available 😊

**Comment by vanhauser-thc** [comment]
the readme is not maintained anymore (that was pre github). all people who add are visible via https://github.com/AFLplusplus/AFLplusplus/graphs/contributors
but I can add you if you want
(I put you in the Changelog)

**Comment by arnow117** [comment]
> the readme is not maintained anymore (that was pre github). all people who add are visible via https://github.com/AFLplusplus/AFLplusplus/graphs/contributors
> but I can add you if you want
> (I put you in the Changelog)

ah nice and thanks ~

**Comment by vanhauser-thc** [comment]
did a 24h run against 2 targets. the first 2-3 hours there was zero difference. after 24h both runs with the fixed mopt were better, one slightly one, one clearly. thanks!

**Comment by vanhauser-thc** [comment]
@arnow117 just saw that there was a larger patch to afl-fuzz in the MOpt repo:
https://github.com/puppet-meteor/MOpt-AFL/commit/040c2950e8ef756412b7a2e12fddf85769009780

the -L1 default is uninteresting and some of the changes are indents as a bracket level was removed- but there are other changes that I cant evaluate if they are good or not. do you have time and experience to have a look?

**Comment by arnow117** [comment]
> @arnow117 just saw that there was a larger patch to afl-fuzz in the MOpt repo:
> [puppet-meteor/MOpt-AFL@040c295](https://github.com/puppet-meteor/MOpt-AFL/commit/040c2950e8ef756412b7a2e12fddf85769009780)
> 
> the -L1 default is uninteresting and some of the changes are indents as a bracket level was removed- but there are other changes that I cant evaluate if they are good or not. do you have time and experience to have a look?

Sorry for delay response...  

I checkout the diff with this [tool](https://sourcegraph.com/github.com/puppet-meteor/MOpt-AFL/-/commit/040c2950e8ef756412b7a2e12fddf85769009780?visible=1), and it seems just move initial work to a new block as default process when mopt-afl start

btw, I find the [newest commit](https://github.com/puppet-meteor/MOpt-AFL/commit/4abab1e5ff6e220ef86135d0166163148d2cd9c4) in MOpt-AFL explain reason for default -L1

**Comment by vanhauser-thc** [comment]
thanks for having a look. if it is just a code move then we can ignore it.
In afl++ we will not make MOpt the default for now I think. This needs way more testing.

**Pull request merged**
