### PR TITLE
Improved FRIDA mode scripting support

### PR DESCRIPTION
**Pull request by WorksButNotTested**

### CODE REVIEW

**Comment by vanhauser-thc** [comment]
what is the improvement? because there is no update to the readme it is just performance?

**Comment by WorksButNotTested** [comment]
> what is the improvement? because there is no update to the readme it is just performance?

The changes are in the Scripting.md. Here…
https://github.com/WorksButNotTested/AFLplusplus/blob/frida-js-2/frida_mode/Scripting.md

**Comment by vanhauser-thc** [comment]
sorry didnt see it as it were too many changes :)

**Comment by WorksButNotTested** [comment]
> sorry didnt see it as it were too many changes :)

No worries. So many little things, they all add up! I’m hoping these changes make it much easier to use.

**Comment by WorksButNotTested** [comment]
Thanks for the merge

**Pull request merged**
