### PR TITLE
llvm_mode Compilation

### PR DESCRIPTION
**Pull request by subho-13**
For Ubuntu 18.04 - To compile llvm_mode, llvm package needs to be installed too.

### CODE REVIEW

**Comment by vanhauser-thc** [comment]
this looks weird. it applies changes we already have in here.

**Comment by subho-13** [comment]
Actually, installing llvm package solves the issue of compiling llvm_mode. So, I added that to the README.md in the parent directory. I made no code changes here.

**Comment by vanhauser-thc** [comment]
well take a look at the changed files in your PR

**Comment by vanhauser-thc** [comment]
I added the change by hand to the repo.
thanks though

**Pull request closed without merging**
