### PR TITLE
Update README: Link to OpenSSF talk added

### PR DESCRIPTION
**Pull request by CowBoy4mH3LL**
Link to short talk at the OpenSSF'24, Linux Foundation added.
Talk contains a short backstory, description and simple demo.

### CODE REVIEW

**Comment by vanhauser-thc** [comment]
Please always put PRs to the dev branch. Thanks :)

**Comment by CowBoy4mH3LL** [comment]
My bad :( -- Will correct that !!

**Comment by domenukk** [comment]
Nothing to do anymore, Marc already changed it to dev. It's just a pointer for the future. :) Thanks!

**Comment by CowBoy4mH3LL** [comment]
Ya saw that after I posted -- Thanks Marc!!

**Pull request merged**
