### PR TITLE
Restore correct CTX behaviour and enable K-CTX coverage for LLVM Classic

### PR DESCRIPTION
**Pull request by andreafioraldi**
The old CTX is now renamed as CALLER, and CTX is now true context-sensitive branch coverage.

As this kind of feedback causes many collisions I introduced the K-CTX branch coverage that takes into account only the top-K functions in the calling context.

### CODE REVIEW

**Comment by andreafioraldi** [comment]
Any considerations before merging?

**Comment by vanhauser-thc** [comment]
ctx-1 is the same as caller - but I guess slower? If so maybe only allow values 2+? if ctx-1 is faster or same speed, then maybe getting rid of caller instead?

**Comment by andreafioraldi** [comment]
when k=1 ctx-1 is automatically converted to caller, that is faster.
What we can do is to distinguish them in the llvm pass but not in afl-cc, having just ctx and k-ctx

**Comment by vanhauser-thc** [comment]
> when k=1 ctx-1 is automatically converted to caller, that is faster.

cool then there is nothing to do IMHO :)

**Pull request merged**
