### PR TITLE
Android Fixes

### PR DESCRIPTION
**Pull request by WorksButNotTested**

### CODE REVIEW

**Comment by WorksButNotTested** [comment]
Is that build error a CI issue or something I’ve broken?

**Comment by GanbaruTobi** [comment]
[errors.log](https://github.com/AFLplusplus/AFLplusplus/files/9035459/errors.log)

**Comment by WorksButNotTested** [comment]
***UPDATE*** I have added this change into the PR, can you try again please @GanbaruTobi? Thanks.

Ah crap. I missed out a header. Can you try adding [this](https://github.com/AFLplusplus/AFLplusplus/blob/ba3c7bfe40f9b17a691958e3525828385127ad25/include/android-ashmem.h#L9)  in [here](https://github.com/AFLplusplus/AFLplusplus/blob/e811c8a0359865fdf215606e575551c386547be2/frida_mode/src/shm.c#L11).

**Comment by GanbaruTobi** [comment]
-- ignore ---
it build, i will try it

**Comment by vanhauser-thc** [comment]
please write to the PR once it can be merged :)

**Comment by GanbaruTobi** [comment]
[errors2.log](https://github.com/AFLplusplus/AFLplusplus/files/9042057/errors2.log)
my bad, it didn't build

**Comment by WorksButNotTested** [comment]
Can you make sys/shm.h included in both configurations (e.g. remove the #else) and try again? @GanbaruTobi thanks.

**Comment by GanbaruTobi** [comment]
[errors3.log](https://github.com/AFLplusplus/AFLplusplus/files/9042081/errors3.log)

**Comment by GanbaruTobi** [comment]
The problem of errors2.log is probably roughly this missing line : https://github.com/aflnet/aflnet/blob/fdcad9d33c6dd53dbac21e6173b7d0aff8ddb494/android-ashmem.h#L30

When adding just that, it builds, but fails on execution with:

image

**Comment by vanhauser-thc** [comment]
@WorksButNotTested @GanbaruTobi 
is this working now or is something still missing?

**Comment by GanbaruTobi** [comment]
This is not working, but @WorksButNotTested has all the information now.
Besides we found that android ashmem pinning is deprecated, which might also affect this code:
https://github.com/AFLplusplus/AFLplusplus/blob/c57988e672634ee98048eba6432cc1f4e377e07c/include/android-ashmem.h#L33

@WorksButNotTested just hit me up when the final changes are applied, i can test again =)

**Comment by WorksButNotTested** [comment]
@GanbaruTobi This should be ready to try again btw. Let me know how you get on.

**Comment by GanbaruTobi** [comment]
[error.log](https://github.com/AFLplusplus/AFLplusplus/files/9229804/error.log)

Still some errors

**Comment by WorksButNotTested** [comment]
@vanhauser-thc This one is ready to merge at last!!!

**Pull request merged**
