### PR TITLE
Fix the issue#2244

### PR DESCRIPTION
**Pull request by fripSide**
Address the [issue#2244](https://github.com/AFLplusplus/AFLplusplus/issues/2244) to ensure that `argv_fuzz_persistent_demo.c` can be successfully compiled without any error messages

### CODE REVIEW

**Comment by vanhauser-thc** [comment]
that is not a fix. yes it does not error anymore, but the issue is that you compile something that needs afl-clang/gcc-fast/lto with outdated afl-gcc/afl-clang. and even if it compiles, it will not work correctly because persistent fuzzing does not work with afl-gcc/afl-clang

**Comment by fripSide** [comment]
Does it work with `afl-clang-fast` ?  Just like [these demos](https://github.com/AFLplusplus/AFLplusplus/tree/stable/utils/persistent_mode).

**Comment by vanhauser-thc** [comment]
> Does it work with `afl-clang-fast` ? Just like [these demos](https://github.com/AFLplusplus/AFLplusplus/tree/stable/utils/persistent_mode).

if you have llvm-dev installed so AFL++ could compile its plugins - sure. just enter "afl-cc" and you see in the help output which instrumentations could be compiled

**Comment by fripSide** [comment]
> > Does it work with `afl-clang-fast` ? Just like [these demos](https://github.com/AFLplusplus/AFLplusplus/tree/stable/utils/persistent_mode).
> 
> if you have llvm-dev installed so AFL++ could compile its plugins - sure. just enter "afl-cc" and you see in the help output which instrumentations could be compiled

The warning message (WARNING: You are using outdated instrumentation) caused by afl-gcc is not related to the current compilation errors. The compilation errors stem from undefined macros, rather than whether you have successfully instrumented.

```
// https://github.com/AFLplusplus/AFLplusplus/blob/stable/utils/argv_fuzzing/argv_fuzz_persistent_demo.c#L10
__AFL_FUZZ_INIT(); // <-------------- __AFL_FUZZ_INIT is not defined

// https://github.com/AFLplusplus/AFLplusplus/blob/stable/utils/argv_fuzzing/argv_fuzz_persistent_demo.c#L23
unsigned char *buf = __AFL_FUZZ_TESTCASE_BUF; // <-------------- __AFL_FUZZ_TESTCASE_BUF is not defined

// https://github.com/AFLplusplus/AFLplusplus/blob/stable/utils/argv_fuzzing/argv_fuzz_persistent_demo.c#L30
int len = __AFL_FUZZ_TESTCASE_LEN; // <-------------- __AFL_FUZZ_TESTCASE_LEN is not defined

```

I do not understand the rationale for closing my issue and pull request while the compiler error remains unresolved. If this demo is no longer needed, it would be better to remove these problematic files (i.e., `argv_fuzz_persistent_demo.c`) from the repository.

**Pull request closed without merging**
