### PR TITLE
Fix two typos.

### PR DESCRIPTION
**Pull request by intrigus-lgtm**

### CODE REVIEW

**Comment by vanhauser-thc** [comment]
should I keep this open in case you find more?

**Comment by intrigus-lgtm** [comment]
Yes, I'm still looking :)

**Comment by intrigus-lgtm** [comment]
@vanhauser-thc I'm done :tada:

**Comment by vanhauser-thc** [comment]
thank you!

**Comment by llzmb** [comment]
Hi @intrigus-lgtm,

thank you for your contribution to the AFL++ docs! You won one of the very rare AFL++ t-shirts (see https://twitter.com/aflplusplus/status/1480836318175408138)!

Please e-mail @vanhauser-thc (mh@mh-sec.de) your address, size, and style (straight or fitted) until this upcoming Friday, January 21st, 2022.

Congrats! 🥳

**Comment by intrigus-lgtm** [comment]
Mail has been sent just now. Hope this still counts :D

**Pull request merged**
