### PR TITLE
Fix pending sub overflow displayed as 4.29G

### PR DESCRIPTION
**Pull request by joeyjiaojg**

### CODE REVIEW

**Comment by vanhauser-thc** [comment]
is this happening on normal usage for you? or have you made changes?
because this should not happen, so the bug is somewhere else - that pending_not_fuzzed is not increased or that a fuzzed one was not marked as done.

**Comment by joeyjiaojg** [comment]
I'm using afl_frida to fuzz, when pending paths reduced to 0, and then it becomes to 4.29G which is u32_max.
I think it's sub overflow?

**Comment by vanhauser-thc** [comment]
> I'm using afl_frida to fuzz, when pending paths reduced to 0, and then it becomes to 4.29G which is u32_max.
> I think it's sub overflow?

sounds like it is an overflow at the location you provide a fix.
but the bug is not that, that is where the real bug impacts.
I will try to to hunt down the real bug on Thursday/Friday, and if I cannot find it then I will accept the PR.
thanks for pointing this issue out!

**Comment by joeyjiaojg** [comment]
ok, thx

**Comment by Zherya** [comment]
Hello! I would like to note that I also face with that bug periodically. For me it was firstly discovered at 3.00c version, as far as I remember. I use Linux OS and a target compiled with GCC and GCC plugin instrumentation. Nothing specific is used or any changes are made. I can try to catch that bug with some additional debug information, if required.

**Comment by vanhauser-thc** [comment]
can you please check if the current dev state still has the same bug behaviour of if it is fixed?
it is not a good fix (if it is fixed), but then helps to refine it.

**Comment by Zherya** [comment]
Sure, will be back with feedback soon

**Comment by Zherya** [comment]
I've restarted (with '-i -' flag and all previous nodes termination) previous fuzzing session in which one of the fuzzing nodes faced with that bug, and got the next error during seed corpus processing (sorry, I'm not able to provide a screenshot):

[-] PROGRAM ABORT : disabled entry? this should not happen, please report!
                      Location : perform_dry_run(), src/afl-fuzz-init.c:1138

**Comment by vanhauser-thc** [comment]
> I've restarted (with '-i -' flag and all previous nodes termination) previous fuzzing session in which one of the fuzzing nodes faced with that bug, and got the next error during seed corpus processing (sorry, I'm not able to provide a screenshot):
> 
> [-] PROGRAM ABORT : disabled entry? this should not happen, please report!
> Location : perform_dry_run(), src/afl-fuzz-init.c:1138

perfect, thats what I hoped :)
I will put a real fix in in a few hours, in the mean time just revert to the previous commit

**Comment by vanhauser-thc** [comment]
@JoeyJiao @Zherya  can you please test the real fix that is in now?

**Comment by Zherya** [comment]
@vanhauser-thc Everything works perfect now, thank you!

**Comment by joeyjiaojg** [comment]
@vanhauser-thc 
but still not work for me.

(gdb) p/x afl->pending_not_fuzzed
$2 = 0xffffffdb

**Comment by joeyjiaojg** [comment]
btw, your fix is only for perform_dry_run, but my case happens after 22 hrs running, so the problem should be exist during fuzz.

**Comment by vanhauser-thc** [comment]
the fix also adds a check in another location but seems to be incomplete. weird.
I have to pinpoint the issue ... 

what are your commandline options and environment variables you use? 
basically the output of `cat out/default/fuzzer_setup`

**Comment by vanhauser-thc** [comment]
@joeyjiaojg I found one more location I missed ... I dont see a possibility how this could happy anymore :) please test

**Pull request closed without merging**
