### PR TITLE
Fix Haiku references, no <sys/syscall.h> and missing defines for USEMMAP

### PR DESCRIPTION
**Pull request by Begasus**

### CODE REVIEW

**Comment by Begasus** [comment]
At least there is another fix needed for undeclared SYS_write, did a dirty hack here, will push the changes later to our haikuports tree if anyone is interested, this PR shouldn't harm other OS's

**Comment by Begasus** [comment]
Current PR at Haikuports: https://github.com/haikuports/haikuports/pull/5815

**Comment by vanhauser-thc** [comment]
thanks. please note that we only accepts PRs to dev, I changed the destination for you.
please resolve the conflict and tell me when the PR is done from your side :)

**Comment by Begasus** [comment]
Thanks @vanhauser-thc , getting rather late here for my doing (mostly up early in the morning), on the conflict I need to see how to do this, not so familiar with this :(

**Comment by vanhauser-thc** [comment]
just remove the line from TODO.md:
https://github.com/AFLplusplus/AFLplusplus/pull/857/files#diff-5c6a1301c6b59b30a040d747d065e861d3dd98bde0e5a4356d92d594e9835986

**Comment by Begasus** [comment]
Thanks! Think that did it, for the base this should be OK for Haiku :)

**Comment by vanhauser-thc** [comment]
what about SYS_write?

**Comment by Begasus** [comment]
> what about SYS_write?

I haven't found a solution for that :( (mind you, I'm not a developer, but been around in BeOS/Haiku for a long time now)
Have been searching on the net, but couldn't find any hints that helped me further :(

**Comment by vanhauser-thc** [comment]
I have never used Haiku, maybe try this:


instead of `long r = syscall(SYS_write, __afl_dummy_fd[1], ptr, len);` do   `long r = _kern_write(__afl_dummy_fd[1], -1, ptr, len);`

**Comment by Begasus** [comment]
> maybe try this:

That seems to work, doing a clean build with a new (local) patchset to be sure :+1:

**Comment by vanhauser-thc** [comment]
Check what the -1 does - should write at current position

**Comment by Begasus** [comment]
From the build:
```
cc -I -I./../include -Wall -g -Wno-cast-qual -Wno-variadic-macros -Wno-pointer-sign -I ./include/ -I ./instrumentation/ -DAFL_PATH=\"/packages/aflplusplus_x86-3.12c-1/.self/lib/x86/afl\" -DBIN_PATH=\"/packages/aflplusplus_x86-3.12c-1/.self/bin\" -DLLVM_BINDIR=\"\" -DVERSION=\"++3.12c\" -DLLVM_LIBDIR=\"\" -DLLVM_VERSION=\"\" -Wno-deprecated -DAFL_CLANG_FLTO=\"\" -DAFL_REAL_LD=\"\" -DAFL_CLANG_LDPATH=\"\" -DAFL_CLANG_FUSELD=\"\" -DCLANG_BIN=\"/clang\" -DCLANGPP_BIN=\"/clang++\" -DUSE_BINDIR=1 -Wno-unused-function  -DUSEMMAP=1  -Wno-unused-result -fPIC -c instrumentation/afl-compiler-rt.o.c -o afl-compiler-rt.o
instrumentation/afl-compiler-rt.o.c: In function '__afl_map_shm':
instrumentation/afl-compiler-rt.o.c:340:16: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
         munmap((void *)__afl_map_addr, __afl_final_loc);
                ^
instrumentation/afl-compiler-rt.o.c:371:16: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
           mmap((void *)__afl_map_addr, __afl_map_size, PROT_READ | PROT_WRITE,
                ^
instrumentation/afl-compiler-rt.o.c:442:9: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
         (void *)__afl_map_addr, __afl_map_size, PROT_READ | PROT_WRITE,
         ^
instrumentation/afl-compiler-rt.o.c:448:15: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
               (void *)__afl_map_addr);
               ^
instrumentation/afl-compiler-rt.o.c: In function '__afl_unmap_shm':
instrumentation/afl-compiler-rt.o.c:601:12: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
     munmap((void *)__afl_map_addr, __afl_map_size);
            ^
instrumentation/afl-compiler-rt.o.c: At top level:
instrumentation/afl-compiler-rt.o.c:1155:1: warning: constructor priorities from 0 to 100 are reserved for the implementation
 __attribute__((constructor(CTOR_PRIO))) void __afl_auto_early(void) {
 ^~~~~~~~~~~~~
instrumentation/afl-compiler-rt.o.c:1167:1: warning: constructor priorities from 0 to 100 are reserved for the implementation
 __attribute__((constructor(1))) void __afl_auto_second(void) {
 ^~~~~~~~~~~~~
instrumentation/afl-compiler-rt.o.c: In function '__afl_auto_second':
instrumentation/afl-compiler-rt.o.c:1183:24: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
       ptr = (u8 *)mmap((void *)__afl_map_addr, __afl_final_loc,
                        ^
instrumentation/afl-compiler-rt.o.c: At top level:
instrumentation/afl-compiler-rt.o.c:1203:1: warning: constructor priorities from 0 to 100 are reserved for the implementation
 __attribute__((constructor(0))) void __afl_auto_first(void) {
 ^~~~~~~~~~~~~
instrumentation/afl-compiler-rt.o.c: In function 'area_is_valid':
instrumentation/afl-compiler-rt.o.c:1743:12: warning: implicit declaration of function '_kern_write' [-Wimplicit-function-declaration]
   long r = _kern_write(__afl_dummy_fd[1], -1, ptr, len);
            ^~~~~~~~~~~
make[1]: llvm-config: Command not found
```

**Comment by vanhauser-thc** [comment]
did you include syscall.h in afl-compiler-rt.o.c ?
is llvm installed? rememer to the LLVM_CONFIG to the llvm-config-VERSION command

**Comment by Begasus** [comment]
> did you include syscall.h in afl-compiler-rt.o.c ?

We don't have syscall.h in Haiku, hence it's disabled in the PR

> is llvm installed? rememer to the LLVM_CONFIG to the llvm-config-VERSION command

We have LLVM (up to version 9), but getting a different error there list ... ```#include <list>``` ... isn't found

**Comment by vanhauser-thc** [comment]
well you should include the include file that has __kern_write

if you have errors with llvm 9 then most likely have not installed all llvm components necessary (e.g. llvm-dev on Linux)

**Comment by devnexen** [comment]
if it helps ... _kern_write seems to be private api not supposed to be exposed (private/system/syscalls.h location that s is), using an extern declaration to expose it might do, not sure of the working tough. also installing `llvm` package should bring llvm-config to the table ;-)

**Comment by Begasus** [comment]
> if you have errors with llvm 9 then most likely have not installed all llvm components necessary (e.g. llvm-dev on Linux)

We do have it, enabling it reports to an error:
```
[+] llvm_mode detected llvm 9, enabling neverZero implementation
[+] llvm_mode detected llvm < 11, afl-lto LTO will not be build.
[-] shmat seems not to be working, switching to mmap implementation
[*] Checking for working 'llvm-config'...
[*] Checking for working '/boot/system/bin/clang'...
[*] Checking for matching versions of '/boot/system/bin/clang' and 'llvm-config'
[*] We have llvm-config version 9.0.1 with a clang version 9.0.1, good.
[*] Checking for './afl-showmap'...
[+] All set and ready to build.
/boot/system/bin/clang++ -DUSEMMAP=1 -g -Wno-pointer-sign -Wno-variadic-macros -Wall -Wextra -Wpointer-arith -I include/ -DAFL_PATH=\"/packages/aflplusplus_x86-3.12c-1/.self/lib/x86/afl\" -DBIN_PATH=\"/packages/aflplusplus_x86-3.12c-1/.self/bin\" -DDOC_PATH=\"/packages/aflplusplus_x86-3.12c-1/.self/documentation/packages/aflplusplus_x86\" -DUSEMMAP=1 -Wno-error=format -fPIC -DUSEMMAP=1 -Wall -g -Wno-cast-qual -Wno-variadic-macros -Wno-pointer-sign -I ./include/ -I ./instrumentation/ -DAFL_PATH=\"/packages/aflplusplus_x86-3.12c-1/.self/lib/x86/afl\" -DBIN_PATH=\"/packages/aflplusplus_x86-3.12c-1/.self/bin\" -DLLVM_BINDIR=\"/boot/system/bin\" -DVERSION=\"++3.12c\" -DLLVM_LIBDIR=\"/boot/system/develop/lib/x86\" -DLLVM_VERSION=\"9.0.1\" -Wno-deprecated -DAFL_CLANG_FLTO=\"\" -DAFL_REAL_LD=\"\" -DAFL_CLANG_LDPATH=\"\" -DAFL_CLANG_FUSELD=\"\" -DCLANG_BIN=\"/boot/system/bin/clang\" -DCLANGPP_BIN=\"/boot/system/bin/clang++\" -DUSE_BINDIR=1 -Wno-unused-function -fdebug-prefix-map="/sources/AFLplusplus-3.12c=llvm_mode" -DUSEMMAP=1  `llvm-config --cxxflags` -fno-rtti -fPIC -std=gnu++11 -c instrumentation/afl-llvm-common.cc -o instrumentation/afl-llvm-common.o 
instrumentation/afl-llvm-common.cc:12:10: fatal error: 'list' file not found
#include <list>
         ^~~~~~
1 error generated.
GNUmakefile.llvm:383: recipe for target 'instrumentation/afl-llvm-common.o' failed
```
**EDIT** wanted to save this for a seperate issue :)

**Comment by Begasus** [comment]
Thanks for chipping in @devnexen :)

**Comment by vanhauser-thc** [comment]
that include error means that you have not installed all necessary llvm packages.

**Comment by vanhauser-thc** [comment]
for linux this needs libc++-LLVMVERSION-dev

**Comment by devnexen** [comment]
would `gcc_syslibs_devel` package help ?

**Comment by Begasus** [comment]
> would `gcc_syslibs_devel` package help ?

Already installed, also all our packages for LLVM9 installed (PS maybe I should mention that I'm running 32bit Haiku with gcc8)
I see the file listed in `/boot/system/develop/headers/x86/c++`

**Comment by devnexen** [comment]
no idea then, I tried your branch locally just replacing manually the syscall line and it get passed the `<list>` missing issue. I use 64 bits image but weird it that counts...

**Comment by Begasus** [comment]
> no idea then, I tried your branch locally just replacing manually the syscall line and it get passed the `<list>` missing issue. I use 64 bits image but weird it that counts...

Probably because in my branch (for haikuports) llvm isn't enabled :)

**Comment by vanhauser-thc** [comment]
the directory has to be auto-searched by GNUmakefile.llvm via `$LLVM_CONFIG --includedir` ... otherwise your installation is broken (or haiku ships a broken installation)

**Comment by Begasus** [comment]
Last comment for today, seems something fishy is going on indeed, I see in other patches `#include <list>` without changes, if I move the line after `#include <string>` it tells me `fatal error: string file not found` ...

**Comment by vanhauser-thc** [comment]
feel free to move it so it compiles :)
our CI will complain if it break Linux.

**Comment by Begasus** [comment]
Think I got it (without moving anything), will report back in the morning :)

**Comment by Begasus** [comment]
After I did a final round in Terminal yesterday it build successfully so I gathered I missed something in the recipe to build it, turns out the suggestion made by @devnexen did the trick (I think it's the first time I had to add `gcc${secondaryArchSuffix}_syslibs_devel` into a recipe).

On the line `long r = _kern_write(__afl_dummy_fd[1], -1, ptr, len);` I can keep it as a patch on our haikuports repository, I don't think it's needed here for other OS's?

I've posted a full build log showing a few errors (that don't break the build though) at: https://paste.ubuntu.com/p/BvtSBTNP9k/
A test run has been posted also (test-libextensions.sh produces a crash) at: https://paste.ubuntu.com/p/Mpvq7nqgMR/
Both links will stay up for a month.

**Comment by devnexen** [comment]
> On the line `long r = _kern_write(__afl_dummy_fd[1], -1, ptr, len);` I can keep it as a patch on our haikuports repository, I don't think it's needed here for other OS's?

You can possibly do a ifdef as alternative, maintaining patches overtime can be taxing (ask the chromium bsd maintainers :-))

**Comment by vanhauser-thc** [comment]
sorry that SYS_write is an essential component of CMPLOG, the best fuzzing mode in afl++. Without this the target will crash.
if you can not use _kern_write then you will need to insert the assembly equivalent. 
Or you fully disable cmplog (via src/afl-cc.c)

**Comment by Begasus** [comment]
Thanks so far @vanhauser-thc , I think I can leave the PR as it is now, should be good to merge, on the issue for SYS_write, maybe I could file a separate issue for it, I'm a bit lost atm as I'm not a developer, maybe @devnexen has some better insight on it (did you try to run it with the current changes/suggestions?)
PS does afl++ have a channel on IRC/freenode?

**Comment by devnexen** [comment]
I meant more something along those lines
`
long r;
#ifdef __HAIKU__
r = _kern_write(__afl_dummy_fd[1], -1, ptr, len)
#else
r = syscall(SYS_write, __afl_dummy_fd[1], ptr, len);
#endif
`

**Comment by Begasus** [comment]
atm pushed a change for this to haikuports:
```diff
-  long r = syscall(SYS_write, __afl_dummy_fd[1], ptr, len);
+  #ifndef __HAIKU__
+    long r = syscall(SYS_write, __afl_dummy_fd[1], ptr, len);
+  #else
+    long r = _kern_write(__afl_dummy_fd[1], -1, ptr, len);
+  #endif // HAIKU
```

**Comment by devnexen** [comment]
It could have been here tough rather than ports but your choice :)

**Comment by Begasus** [comment]
> It could have been here tough rather than ports but your choice :)

If this is acceptable I can push it here also

**Comment by vanhauser-thc** [comment]
sure this can be here

**Comment by Begasus** [comment]
Ok, pushed, at haikuports I also added a post-install script to create the debug_server directory when it's not present @devnexen :)
If this gets merged the current patchset on haikuports should be good to remove for the next release here :)

**Comment by devnexen** [comment]
Little detail, you need to declare, somewhere,  _kern_write as it is private api ... something along those lines.
`
extern ssize_t _kern_write(int fd, off_t pos, const void *buffer, size_t bufferSize); 
`
otherwise you re likely to get implicit declaration ... warning

**Comment by Begasus** [comment]
Added it locally here after line: https://github.com/AFLplusplus/AFLplusplus/blob/stable/instrumentation/afl-compiler-rt.o.c#L78 (not sure if it's correct) with (warning is gone now):
```diff
+#if defined(__HAIKU__)
+  extern ssize_t _kern_write(int fd, off_t pos, const void *buffer, size_t bufferSize);
+#endif
+
```

**Comment by vanhauser-thc** [comment]
> Added it locally here after line: https://github.com/AFLplusplus/AFLplusplus/blob/stable/instrumentation/afl-compiler-rt.o.c#L78 (not sure if it's correct) with (warning is gone now):
> 
> ```diff
> +#if defined(__HAIKU__)
> +  extern ssize_t _kern_write(int fd, off_t pos, const void *buffer, size_t bufferSize);
> +#endif
> +
> ```

but this is not in this PR

**Comment by vanhauser-thc** [comment]
also, please check if your fix works:

`./afl-clang-fast -o test-instr test-instr.c`

**Comment by Begasus** [comment]
> but this is not in this PR

Wanted to make sure the place I put it was good before I pushed it here :)

> also, please check if your fix works:

Not sure what it should produce, but here is the output:

```
Welcome to the Haiku shell.
/Opslag/haikuports/app-forensics/aflplusplus/work-x86-3.12c/sources/AFLplusplus-3.12c> ./afl-clang-fast -o test-instr test-instr.c 
afl-cc ++3.12c by Michal Zalewski, Laszlo Szekeres, Marc Heuse - mode: LLVM-PCGUARD
Using unoptimized trace-pc-guard, upgrade to llvm 10.0.1+ for enhanced version.
/Opslag/haikuports/app-forensics/aflplusplus/work-x86-3.12c/sources/AFLplusplus-3.12c>
```

**EDIT** Wasn't sure I needed to run the binary after the test, but here is the output:
```
./test-instr -h
Input -h - Neiter one or zero? How quaint!
./test-instr -1
Input 1 - Pretty sure that is a one!
./test-instr -152
Input 152 - Pretty sure that is a one!
./test-instr -0
Input _ - Looks like a zero to me!
```

**Comment by Begasus** [comment]
While we are at it :)
I see in the build lines like `byte-compiling build/bdist.linux-x86_64/egg/unicornafl/arm_const.py to arm_const.cpython-36.pyc`
I haven't seen them in a  local build here, could it be that I'm missing something there?

**Comment by vanhauser-thc** [comment]
Unicorn is based on Qemu and I am sure this does not build on Haiku so this can be ignored.
PR looks good to me, thank you!

**Comment by Begasus** [comment]
Thanks for the help and the patience @vanhauser-thc and @devnexen !

**Comment by devnexen** [comment]
> Unicorn is based on Qemu and I am sure this does not build on Haiku so this can be ignored.
> PR looks good to me, thank you!

It might at some point tough https://github.com/unicorn-engine/unicorn/blob/e639d3fc93286f31b395085d1419fc7db60d53ac/Makefile#L207 no surprise qemu had haiku support since few releases (I did the ground work support last summer).

**Comment by hexcoder-** [comment]
Thanks @Begasus and @devnexen for good progress!
I updated my Haiku and got the following results:

- two compiler warnings regarding `random()`. The cause is a non standard (POSIX) function prototype in Haiku
- the afl-*-fast compilers do not produce working feedback (cause unknown yet)
- afl-cc, afl-clang and afl-clang-fast need `-fPIC` for linking targets
- afl-gcc works.

**Comment by Begasus** [comment]
Thanks on the feedback @hexcoder- , on the first 2 I'm not sure (would need some investigation), nr 3 should be an easy fix (I think) :+1: 
**EDIT** although the local copy builds fine here (on R1B2 32bit (and I think @devnexen also did a successful build on 64bit)) the build seems to error on our buildbot, first indication was a wrong clang version, but that didn't even seem to solve the issue, need to investigate that too: https://build.haiku-os.org/buildmaster/master/x86_gcc2/logviewer.html?buildruns/1356/builds/2375.log

**Comment by Begasus** [comment]
>     * afl-cc, afl-clang and afl-clang-fast need `-fPIC` for linking

Looking at: https://github.com/Begasus/AFLplusplus/blob/43b1a0d46bd7fb55e2baeadd5d105e60aecdee9c/GNUmakefile#L166 it should already be there?

**Comment by hexcoder-** [comment]
Yes, the afl-tools are build correctly. I meant the compiled targets. Their compilation needs `-fPIC`, otherwise there are linker errors.

**Pull request merged**
