### PR TITLE
Install {config,types}.h

### LINKED ISSUE #2233: Install data headers
I'm packaging (my fork of) [afl-dyninst](https://github.com/vanhauser-thc/afl-dyninst) for Guix.  While it's technically trivial to patch AFL++ downstream to install standalone data headers, it's always nicer not having to maintain downstream patches.

afl-dyninst uses 2 AFL's internal headers: config.h and types.h.  I suggest installing under the afl namespace (since the binaries are still `afl-*`), i.e. $PREFIX/include/afl.

### PR DESCRIPTION
**Pull request by McSinyx**
Resolves GH-2233.

### CODE REVIEW

**Comment by vanhauser-thc** [comment]
Lgtm, thanks!

**Comment by McSinyx** [comment]
Thank for the quick merge!  BTW is there an ETA for 4.22c?

**Comment by vanhauser-thc** [comment]
Not yet. Between mid of November and new year :)

**Comment by McSinyx** [comment]
Thanks, that's sooner than I expected!

**Pull request merged**
