### PR TITLE
android: disable sigaction inside debuggerd

### PR DESCRIPTION
**Pull request by joeyjiaojg**
check https://github.com/google/AFL/blob/master/docs/INSTALL#L173

### CODE REVIEW

**Review by hexcoder- — APPROVED** [review]
Thanks!

**Comment by vanhauser-thc** [comment]
@hexcoder- that was too early! :)

@joeyjiaojg we were discussing this PR internally. When compiling with ASAN, this hijacks signals, so likely this patch will not work with asan on android? have you tested this?
If asan makes problems with this, you can try moving the setting to `__afl_auto_first()` which might be before asan.

**Comment by andreafioraldi** [comment]
__afl_auto_first is nto before asan because sanitizers use the preinit array

**Comment by joeyjiaojg** [comment]
Can you explain more why asan breaks?
ASAN for AFL++ on Android breaks even before this change, so I mainly use AFL++ only for afl-frida.

**Comment by vanhauser-thc** [comment]
we are not saying "does break", only "could break". I recommend testing with asan and the signal handler reset if things still work for you.

**Comment by joeyjiaojg** [comment]
> __afl_auto_first is nto before asan because sanitizers use the preinit array

right, .preinit_array initialized in linker before calling the constructor.
Anyhow, I haven't succeeded to bisect asan failure reason yet.

**Comment by joeyjiaojg** [comment]
No matter if I enabled the signal patch or not, HWAddressSanitizer always crashes the target binary.

It breaks in this line
```
  if (getenv("AFL_DISABLE_LLVM_INSTRUMENTATION")) return;
```
Which seems not reasonable to me.

**Pull request merged**
