### PR TITLE
Use direct call to write to OpenBSD

### PR DESCRIPTION
**Pull request by jasperla**
The linker on OpenBSD emits a warning when linking this file: warning: syscall() may go away, please rewrite code to use direct calls.

Other `syscall()` invocations in AFLplusplus code aren't compiled on OpenBSD at the moment.

### CODE REVIEW

**Comment by vanhauser-thc** [comment]
the purpose of this syscall is to circumvent libc and asan, I fear this will break then on openbsd. is there an alternative like for haiku?

**Comment by jasperla** [comment]
There is no alternative as far as I know, the whole point of removing `syscall(2)` is by forcing application to go through libc. The risk of breaking ASAN on OpenBSD is an acceptable trade-off compared to not having AFL at all.

**Comment by devnexen** [comment]
I think it s safe in asan side, openbsd does not have support for it, not even ubsan unless openbsd did its own asan ?

**Comment by vanhauser-thc** [comment]
Ok :)

**Pull request merged**
