### PR TITLE
Fix links in FAQ.md

### PR DESCRIPTION
**Pull request by yuawn**
Fix relative path in docs/FAQ.md.

### CODE REVIEW

**Comment by vanhauser-thc** [comment]
you are right that the links are outdated, however you fix is incomplete :)
the referenced docs are in instrumentation/... but as the FAQ.md is in docs/ it would need to be ../instrumentation/foobar.md
you are using /instrumentation in most placed instead, but that does not work well either.

**Comment by yuawn** [comment]
I tested it, it works in web.
But still change it to ../instrumentation.

**Comment by yuawn** [comment]
@vanhauser-thc done!

**Comment by vanhauser-thc** [comment]
yes it would work on github, but not once it is checked out anymore. now its fine, thank you.

**Pull request merged**
