### PR TITLE
Fix afl-gcc

### LINKED ISSUE #2058: afl-gcc doesn't instrument anymore
Hello,

After updating the package alfplusplus in Debian, one of the tests doesn't work anymore. It seems that something broke in `afl-gcc`.

Here's a trace for **working** afl-gcc (version `4.09c-1`):

```
# export AFL_DEBUG=1

# afl-gcc     test-instr.c   -o test-instr
[D] DEBUG: Trying /usr/bin/../lib/afl/SanitizerCoverageLTO.so
[D] DEBUG: Trying /usr/bin/../lib/afl/cmplog-routines-pass.so
[D] DEBUG: Trying /usr/bin/../lib/afl/afl-gcc-pass.so
afl-cc++4.09c by Michal Zalewski, Laszlo Szekeres, Marc Heuse - mode: GCC-GCC
[!] WARNING: You are using outdated instrumentation, install LLVM and/or gcc-plugin and use afl-clang-fast/afl-clang-lto/afl-gcc-fast instead!
[D] DEBUG: cd '/work/4.09c-1'; 'afl-gcc' 'test-instr.c' '-o' 'test-instr'
[D] DEBUG: Trying /usr/bin/../lib/afl/afl-compiler-rt.o
[D] DEBUG: rt=/usr/bin/../lib/afl/afl-compiler-rt.o obj_path=/usr/bin/../lib/afl/
[D] DEBUG: cd '/work/4.09c-1'; 'gcc' '-B' '/usr/bin/../lib/afl/' 'test-instr.c' '-o' 'test-instr' '-fPIC' '-g' '-O3' '-funroll-loops' '-D__AFL_COMPILER=1' '-DFUZZING_BUILD_MODE_UNSAFE_FOR_PRODUCTION=1' '-D__AFL_COVERAGE()=int __afl_selective_coverage = 1;void __afl_coverage_discard();void __afl_coverage_skip();void __afl_coverage_on();void __afl_coverage_off();' '-D__AFL_COVERAGE_START_OFF()=int __afl_selective_coverage_start_off = 1;' '-D__AFL_COVERAGE_ON()=__afl_coverage_on()' '-D__AFL_COVERAGE_OFF()=__afl_coverage_off()' '-D__AFL_COVERAGE_DISCARD()=__afl_coverage_discard()' '-D__AFL_COVERAGE_SKIP()=__afl_coverage_skip()' '-D__AFL_FUZZ_TESTCASE_BUF=(__afl_fuzz_ptr ? __afl_fuzz_ptr : __afl_fuzz_alt_ptr)' '-D__AFL_FUZZ_TESTCASE_LEN=(__afl_fuzz_ptr ? *__afl_fuzz_len : (*__afl_fuzz_len = read(0, __afl_fuzz_alt_ptr, 1048576)) == 0xffffffff ? 0 : *__afl_fuzz_len)'
afl-as++4.09c by Michal Zalewski
[+] Instrumented 19 locations (64-bit, non-hardened mode, ratio 100%).
```

And now is **non-working** afl-gcc (version `4.20c-1`):

```
# export AFL_DEBUG=1

# afl-gcc     test-instr.c   -o test-instr
[D] DEBUG: Trying /usr/bin/../lib/afl/SanitizerCoveragePCGUARD.so
[D] DEBUG: Trying /usr/bin/../lib/afl/SanitizerCoverageLTO.so
[D] DEBUG: Trying /usr/bin/../lib/afl/cmplog-routines-pass.so
[D] DEBUG: Trying /usr/bin/../lib/afl/afl-gcc-pass.so
[D] DEBUG: Trying /usr/bin/../lib/afl/afl-compiler-rt.o
[D] DEBUG: rt=/usr/bin/../lib/afl/afl-compiler-rt.o
afl-cc++4.20c by Michal Zalewski, Laszlo Szekeres, Marc Heuse - mode: GCC-GCC
[!] WARNING: You are using outdated instrumentation, install LLVM and/or gcc-plugin and use afl-clang-fast/afl-clang-lto/afl-gcc-fast instead!
[D] DEBUG: cd '/work/4.20c-1'; 'afl-gcc' 'test-instr.c' '-o' 'test-instr'
[D] DEBUG: cd '/work/4.20c-1'; 'gcc' '-B' '/usr/bin' 'test-instr.c' '-o' 'test-instr' '-fPIC' '-g' '-O3' '-funroll-loops' '-D__AFL_COMPILER=1' '-DFUZZING_BUILD_MODE_UNSAFE_FOR_PRODUCTION=1' '-D__AFL_COVERAGE()=int __afl_selective_coverage = 1;void __afl_coverage_discard();void __afl_coverage_skip();void __afl_coverage_on();void __afl_coverage_off();' '-D__AFL_COVERAGE_START_OFF()=int __afl_selective_coverage_start_off = 1;' '-D__AFL_COVERAGE_ON()=__afl_coverage_on()' '-D__AFL_COVERAGE_OFF()=__afl_coverage_off()' '-D__AFL_COVERAGE_DISCARD()=__afl_coverage_discard()' '-D__AFL_COVERAGE_SKIP()=__afl_coverage_skip()' '(null)'
```

In this second trace, what's missing is the last line: `[+] Instrumented 19 locations (64-bit, non-hardened mode, ratio 100%).`

Comparing the 2 traces now...

First difference that stands out: for `4.09c-1`, the line `Trying /usr/bin/../lib/afl/afl-gcc-pass.so` triggers something (it's followed by a line `afl-cc++4.09c...`), while it doesn't trigger anything in version `4.20c-1`.... But, that's assuming logs come in order, is it true?

The actual issue is the value for the `-B` parameter given to gcc. For `4.09c-1` we have `'gcc' '-B' '/usr/bin/../lib/afl/'` while for `4.20c-1` we have `'gcc' '-B' '/usr/bin'`.. That's the problem.

By running the gcc line manualy, and fixing this value, it seems that I can get it to work:

```
# 'gcc' '-B' '/usr/bin/../lib/afl/' 'test-instr.c' '-o' 'test-instr' '-fPIC' '-g' '-O3' '-funroll-loops' '-D__AFL_COMPILER=1' '-DFUZZING_BUILD_MODE_UNSAFE_FOR_PRODUCTION=1' '-D__AFL_COVERAGE()=int __afl_selective_coverage = 1;void __afl_coverage_discard();void __afl_coverage_skip();void __afl_coverage_on();void __afl_coverage_off();' '-D__AFL_COVERAGE_START_OFF()=int __afl_selective_coverage_start_off = 1;' '-D__AFL_COVERAGE_ON()=__afl_coverage_on()' '-D__AFL_COVERAGE_OFF()=__afl_coverage_off()' '-D__AFL_COVERAGE_DISCARD()=__afl_coverage_discard()' '-D__AFL_COVERAGE_SKIP()=__afl_coverage_skip()'
afl-as++4.20c by Michal Zalewski
[+] Instrumented 19 locations (64-bit, non-hardened mode, ratio 100%).
```

There's been some heavy refactoring of `src/afl-cc.c` between `4.09` and `4.20` so I suppose something broke.

I'm trying to find out what exactly, I'll follow up, but if someone can already give some hints at this point, that would be lovely!

Thanks!

### PR DESCRIPTION
**Pull request by elboulangero**
Close: #2058

### CODE REVIEW

**Comment by SonicStark** [comment]
1. AFLplusplus do not accept PRs to main, only to dev.
2. Line 521 in afl-cc.c https://github.com/AFLplusplus/AFLplusplus/blob/6b049536f1614892df99f7c1ebd7710192b607a8/src/afl-cc.c#L521 should also be fixed as
   ```c
   ptr = find_object(aflcc, "afl-as")) != NULL)
   ```
   due to the same bug.
3. IMO, we need to check if the `as` found is exactly what we need after https://github.com/AFLplusplus/AFLplusplus/blob/6b049536f1614892df99f7c1ebd7710192b607a8/src/afl-cc.c#L2481
   just sth like
   ```c
   s32 fd;
   u8* f_data;
   u32 f_len = 0;
   
   u8 *afl_as_symlink = alloc_printf("%s/as", afl_as);
   
   fd = open(afl_as_symlink, O_RDONLY);
   
   if (fd < 0) PFATAL("Cannot open '%s' (should be a symlink or copy of 'afl-as').", afl_as_symlink);
   
   f_data = mmap(0, f_len, PROT_READ, MAP_PRIVATE, fd, 0);
   
   if (f_data == MAP_FAILED) PFATAL("Unable to mmap file '%s'", afl_as_symlink);
   
   close(fd);
   
   if (!memmem(f_data, f_len, "AFL_AS", strlen("AFL_AS") + 1)) {
     FATAL("Looks like '%s' is not a valid symlink or copy of 'afl-as'");
   }
   
   if (munmap(f_data, f_len)) PFATAL("unmap() failed");
   
   ck_free(afl_as_symlink);
   ```
   I can open another PR to do this, or just push commits to your forked branch if it is convenient to you :)

**Comment by vanhauser-thc** [comment]
Please do fixes in this PR

**Comment by SonicStark** [comment]
Here is my patch [git-diff.txt](https://github.com/AFLplusplus/AFLplusplus/files/15000604/git-diff.txt) based on b33a5be2ad3f752597ab53a6a1a26b5b8743db02 @elboulangero :
```diff
diff --git a/src/afl-cc.c b/src/afl-cc.c
index 15e0fcc7..e0394f15 100644
--- a/src/afl-cc.c
+++ b/src/afl-cc.c
@@ -17,6 +17,10 @@
 
 #define AFL_MAIN
 
+#ifndef _GNU_SOURCE
+  #define _GNU_SOURCE 1
+#endif
+
 #include "common.h"
 #include "config.h"
 #include "types.h"
@@ -32,7 +36,9 @@
 #include <limits.h>
 #include <assert.h>
 #include <ctype.h>
+#include <fcntl.h>
 #include <sys/stat.h>
+#include <sys/mman.h>
 
 #if (LLVM_MAJOR - 0 == 0)
   #undef LLVM_MAJOR
@@ -520,7 +526,7 @@ void find_built_deps(aflcc_state_t *aflcc) {
   char *ptr = NULL;
 
 #if defined(__x86_64__)
-  if ((ptr = find_object(aflcc, "as")) != NULL) {
+  if ((ptr = find_object(aflcc, "afl-as")) != NULL) {
 
   #ifndef __APPLE__
     // on OSX clang masquerades as GCC
@@ -2482,6 +2488,53 @@ void add_assembler(aflcc_state_t *aflcc) {
   u8 *slash = strrchr(afl_as, '/');
   if (slash) *slash = 0;
 
+  // Search for 'as' may be unreliable in some cases (see #2058)
+  // so use 'afl-as' instead, because 'as' is usually a symbolic link,
+  // or can be a renamed copy of 'afl-as' created in the same dir.
+  // Now we should verify if the compiler can find the 'as' we need.
+
+#define AFL_AS_ERR "(should be a symlink or copy of 'afl-as')"
+
+  u8 *afl_as_dup = alloc_printf("%s/as", afl_as);
+
+  int fd = open(afl_as_dup, O_RDONLY);
+  if (fd < 0) { PFATAL("Unable to open '%s' " AFL_AS_ERR, afl_as_dup); }
+
+  struct stat st;
+  if (fstat(fd, &st) < 0) {
+
+    PFATAL("Unable to fstat '%s' " AFL_AS_ERR, afl_as_dup);
+
+  }
+
+  u32 f_len = st.st_size;
+
+  u8 *f_data = mmap(0, f_len, PROT_READ, MAP_PRIVATE, fd, 0);
+  if (f_data == MAP_FAILED) {
+
+    PFATAL("Unable to mmap file '%s' " AFL_AS_ERR, afl_as_dup);
+
+  }
+
+  close(fd);
+
+  // "AFL_AS" is a const str passed to getenv in afl-as.c
+  if (!memmem(f_data, f_len, "AFL_AS", strlen("AFL_AS") + 1)) {
+
+    FATAL(
+        "Looks like '%s' is not a valid symlink or copy of '%s/afl-as'. "
+        "It is a prerequisite to override system-wide 'as' for "
+        "instrumentation.",
+        afl_as_dup, afl_as);
+
+  }
+
+  if (munmap(f_data, f_len)) { PFATAL("unmap() failed"); }
+
+  ck_free(afl_as_dup);
+
+#undef AFL_AS_ERR
+
   insert_param(aflcc, "-B");
   insert_param(aflcc, afl_as);
 

```

**Comment by elboulangero** [comment]
I tested the patch above, it builds and everything still works. Thanks @SonicStark !

**Comment by vanhauser-thc** [comment]
@elboulangero can you please merge the patch into your PR?

**Comment by elboulangero** [comment]
@vanhauser-thc Pushed it

**Comment by elboulangero** [comment]
I also rebased it on the `dev` branch

**Comment by vanhauser-thc** [comment]
thank you!

**Pull request merged**
