### PR TITLE
Fix unicornafl static build

### PR DESCRIPTION
**Pull request by wtdcode**
This fixes unicornafl C sample.

### CODE REVIEW

**Comment by vanhauser-thc** [comment]
this seems to have a side effect:
```
[*] running afl-fuzz for unicorn_mode compcov, this will take approx 35 seconds
CUT------------------------------------------------------------------CUT
[u] [165620] uc_hook_block address=0x0 cur_loc=0 prev_loc=0
[u] [165620] We are stopping for uc_err=6 (Invalid memory read (UC_ERR_READ_UNMAPPED))
[u] [165620] UC returned Error: 'Invalid memory read (UC_ERR_READ_UNMAPPED)' - let's abort().
[+] Loaded environment variable AFL_PATH with value /home/runner/work/AFLplusplus/AFLplusplus/test/..
[+] Loaded environment variable AFL_EXIT_ON_TIME with value 60
[+] Loaded environment variable AFL_DEBUG_CHILD with value 1
[+] Loaded environment variable AFL_NO_AFFINITY with value 1
[+] Loaded environment variable AFL_SKIP_CPUFREQ with value 1
[+] Loaded environment variable AFL_I_DONT_CARE_ABOUT_MISSING_CRASHES with value 1
[+] Loaded environment variable AFL_EXIT_WHEN_DONE with value 1
afl-fuzz++4.01a based on afl by Michal Zalewski and a large online community
[+] afl++ is maintained by Marc "van Hauser" Heuse, Heiko "hexcoder" Eißfeldt, Andrea Fioraldi and Dominik Maier
[+] afl++ is open source, get it at https://github.com/AFLplusplus/AFLplusplus
[+] NOTE: This is v3.x which changes defaults and behaviours - see README.md
[+] Loaded environment variable ASAN_OPTIONS with value detect_leaks=0:allocator_may_return_null=1:abort_on_error=1:symbolize=0
[+] No -M/-S set, autoconfiguring for "-S default"
[*] Getting to work...
[+] Using exponential power schedule (FAST)
[+] Enabled testcache with 50 MB
[+] Generating fuzz data with a a length of min=1 max=1048576
[*] Checking core_pattern...
[+] Looks like we're not running on a tty, so I'll be a bit less verbose.
[+] You have 2 CPU cores and 1 runnable tasks (utilization: 50%).
[+] Try parallel jobs - see docs/parallel_fuzzing.md.
[*] Setting up output directories...
[+] Output directory exists but deemed OK to reuse.
[*] Deleting old session data...
[+] Output dir cleanup successful.
[!] WARNING: Not binding to a CPU core (AFL_NO_AFFINITY set).
[*] Scanning 'in'...
[+] Loaded a total of 1 seeds.
[*] Creating hard links for all input files...
[*] Validating target binary...
[*] No auto-generated dictionary tokens to reuse.
[*] Attempting dry run with 'id:000000,time:0,execs:0,orig:in'...
[*] Spinning up the fork server...
[+] All right - fork server is up.
[*] Using SHARED MEMORY FUZZING feature.

[-] Oops, the program crashed with one of the test cases provided. There are
    several possible explanations:

    - The test case causes known crashes under normal working conditions. If
      so, please remove it. The fuzzer should be seeded with interesting
      inputs - but not ones that cause an outright crash.

    - In QEMU persistent mode the selected address(es) for the loop are not
      properly cleaning up variables and memory. Try adding
      AFL_QEMU_PERSISTENT_GPR=1 or select better addresses in the binary.

    - Least likely, there is a horrible bug in the fuzzer. If other options
      fail, poke <afl-users@googlegroups.com> for troubleshooting tips.
[!] WARNING: Test case 'id:000000,time:0,execs:0,orig:in' results in a crash, skipping
[+] All test cases processed.
25h
[-] PROGRAM ABORT : We need at least one valid input seed that does not crash!
         Location : main(), src/afl-fuzz.c:2178

CUT------------------------------------------------------------------CUT
[!] afl-fuzz is not working correctly with unicorn_mode compcov
```

**Comment by wtdcode** [comment]
> this seems to have a side effect:
> 
> ```
> [*] running afl-fuzz for unicorn_mode compcov, this will take approx 35 seconds
> CUT------------------------------------------------------------------CUT
> [u] [165620] uc_hook_block address=0x0 cur_loc=0 prev_loc=0
> [u] [165620] We are stopping for uc_err=6 (Invalid memory read (UC_ERR_READ_UNMAPPED))
> [u] [165620] UC returned Error: 'Invalid memory read (UC_ERR_READ_UNMAPPED)' - let's abort().
> [+] Loaded environment variable AFL_PATH with value /home/runner/work/AFLplusplus/AFLplusplus/test/..
> [+] Loaded environment variable AFL_EXIT_ON_TIME with value 60
> [+] Loaded environment variable AFL_DEBUG_CHILD with value 1
> [+] Loaded environment variable AFL_NO_AFFINITY with value 1
> [+] Loaded environment variable AFL_SKIP_CPUFREQ with value 1
> [+] Loaded environment variable AFL_I_DONT_CARE_ABOUT_MISSING_CRASHES with value 1
> [+] Loaded environment variable AFL_EXIT_WHEN_DONE with value 1
> afl-fuzz++4.01a based on afl by Michal Zalewski and a large online community
> [+] afl++ is maintained by Marc "van Hauser" Heuse, Heiko "hexcoder" Eißfeldt, Andrea Fioraldi and Dominik Maier
> [+] afl++ is open source, get it at https://github.com/AFLplusplus/AFLplusplus
> [+] NOTE: This is v3.x which changes defaults and behaviours - see README.md
> [+] Loaded environment variable ASAN_OPTIONS with value detect_leaks=0:allocator_may_return_null=1:abort_on_error=1:symbolize=0
> [+] No -M/-S set, autoconfiguring for "-S default"
> [*] Getting to work...
> [+] Using exponential power schedule (FAST)
> [+] Enabled testcache with 50 MB
> [+] Generating fuzz data with a a length of min=1 max=1048576
> [*] Checking core_pattern...
> [+] Looks like we're not running on a tty, so I'll be a bit less verbose.
> [+] You have 2 CPU cores and 1 runnable tasks (utilization: 50%).
> [+] Try parallel jobs - see docs/parallel_fuzzing.md.
> [*] Setting up output directories...
> [+] Output directory exists but deemed OK to reuse.
> [*] Deleting old session data...
> [+] Output dir cleanup successful.
> [!] WARNING: Not binding to a CPU core (AFL_NO_AFFINITY set).
> [*] Scanning 'in'...
> [+] Loaded a total of 1 seeds.
> [*] Creating hard links for all input files...
> [*] Validating target binary...
> [*] No auto-generated dictionary tokens to reuse.
> [*] Attempting dry run with 'id:000000,time:0,execs:0,orig:in'...
> [*] Spinning up the fork server...
> [+] All right - fork server is up.
> [*] Using SHARED MEMORY FUZZING feature.
> 
> [-] Oops, the program crashed with one of the test cases provided. There are
>     several possible explanations:
> 
>     - The test case causes known crashes under normal working conditions. If
>       so, please remove it. The fuzzer should be seeded with interesting
>       inputs - but not ones that cause an outright crash.
> 
>     - In QEMU persistent mode the selected address(es) for the loop are not
>       properly cleaning up variables and memory. Try adding
>       AFL_QEMU_PERSISTENT_GPR=1 or select better addresses in the binary.
> 
>     - Least likely, there is a horrible bug in the fuzzer. If other options
>       fail, poke <afl-users@googlegroups.com> for troubleshooting tips.
> [!] WARNING: Test case 'id:000000,time:0,execs:0,orig:in' results in a crash, skipping
> [+] All test cases processed.
> �25h
> [-] PROGRAM ABORT : We need at least one valid input seed that does not crash!
>          Location : main(), src/afl-fuzz.c:2178
> 
> CUT------------------------------------------------------------------CUT
> [!] afl-fuzz is not working correctly with unicorn_mode compcov
> ```

How to reproduce this?

**Comment by vanhauser-thc** [comment]
these are the test scripts that run in the CI:
```
cd test
./test-unicorn.sh
```
side note: if you want you can edit the file and add feature tests.

**Comment by wtdcode** [comment]
Done

**Comment by wtdcode** [comment]
The unicornafl python bindings breaks for the pypi unicorn version so the test fails here. One solution is to force re-install unicorn bindings from the source when building unicorn mode (currently it's from pypi) but I'm not sure whether it's too aggressive for end users.

If that's not possible, this can be merged after next Unicorn python release.

**Comment by domenukk** [comment]
I think installing from source makes sense here? At least for the tests, else the CI is decoupled from the actual code

**Comment by vanhauser-thc** [comment]
what should we do here?
there is  a conflict too.

**Comment by wtdcode** [comment]
> what should we do here?
> there is a conflict too.

Nothing more on AFL side and I will fix the conflicts and CI.

**Comment by vanhauser-thc** [comment]
@wtdcode when can you finish this? we want to push to the stable branch and are waiting for this PR :)

**Comment by wtdcode** [comment]
> @wtdcode when can you finish this? we want to push to the stable branch and are waiting for this PR :)

Would have a look tonight. Since unicorn has been released, it should be fine to use pypi package for now.

**Comment by domenukk** [comment]
I still think CI should be testing the actual code rather than a random version from the web, else we don't catch bugs when they are introduced

**Comment by wtdcode** [comment]
> I still think CI should be testing the actual code rather than a random version from the web, else we don't catch bugs when they are introduced

Yes, exactly but for this PR leaving it there should be fine. I would draft another PR to make sure CI uses the unicorn repo within unicornafl repo.

**Comment by vanhauser-thc** [comment]
thank you!

**Pull request merged**
