### PR TITLE
Added CFISAN option for verbose output on crash

### PR DESCRIPTION
**Pull request by StepanGulyaev**
Hello. Me and @Fahnenfluchtige added compile option to CFISAN for it to print verbose output on crash instead of "Illegal Instruction". It's pretty similar to the thing we wrote about UBSAN yesterday: https://github.com/AFLplusplus/AFLplusplus/issues/2247. Program crashes as it should and also prints place where during the crash reproduction:

изображение

изображение

### CODE REVIEW

**Comment by vanhauser-thc** [comment]
Adding verbose output to a crash that is compiled for fuzzing will impact the fuzzing speed (each crash will take longer).
this should only be activated with a special env var (eg. `AFL_VERBOSE_SANITIZERS`) at compile time.

**Comment by StepanGulyaev** [comment]
Oh, I see. Thank you, we will work on that. I think we should do it only for CFISAN for now.

**Comment by StepanGulyaev** [comment]
Also shouldn't we have same approach with VERBOSE variable on UBSAN? After fix yesterday it always prints verbose output because of -fno-sanitize-recover=all, maybe we should use "-fsanitize-trap=undefined" if VERBOSE variable not set

https://github.com/AFLplusplus/AFLplusplus/blob/3af042d5bf3116a194168f5d1e40311a484959e8/src/afl-cc.c#L1951

**Comment by vanhauser-thc** [comment]
can you please add the env description to docs/env_variables.md ? thank you!

**Comment by StepanGulyaev** [comment]
We'll surely add. Thank you

**Comment by vanhauser-thc** [comment]
thank you!

**Pull request merged**
