### PR TITLE
Port the fauxserver changes to afl-cmplog and code format

### PR DESCRIPTION
**Pull request by rish9101**

### CODE REVIEW

**Comment by domenukk** [comment]
@andreafioraldi This looks good but I don't have a cmplog target/setup. Can you try it out quickly? Else I'll do it tomorrow.

**Comment by andreafioraldi** [comment]
Yep I'll try in in minutes

**Comment by vanhauser-thc** [comment]
@rish9101 can you please close and re-submit the PR? By moving the repo to the new organisation it would not commit to "dev" which is now the new target for all PRs. Thanks!

**Comment by domenukk** [comment]
Not needed, I changed it manually

**Comment by vanhauser-thc** [comment]
@domenukk @rish9101 what is the status here? Does it still need work? or why is not not merged?

**Comment by andreafioraldi** [comment]
I'm testing it right now, not enough time yesterday evening.

**Comment by andreafioraldi** [comment]
Btw timeouts in CmpLog are not so important, it is executed only one time for each queue entry.

**Comment by andreafioraldi** [comment]
Using this program:
```c
  1 int main() {                                                                    
  2   srand(time(0));                                                                 
  3   unsigned a;                                                                   
  4   read(0, &a, 4);                                                               
  5                                                                                 
  6   if (a != 0x41414141 && (rand() % 2) == 0){ printf("sleeping\n"); sleep(10000); }
  7                                                                                 
  8 }   
```

And putting a print when the cmplog forkserver restart the child due to a timeout seems to work.

**Comment by andreafioraldi** [comment]
I'll let the fuzzer run for some time, meanwhile I merge the PR, ty @rish9101.
IMO at 99% it is fine, if the fuzzer gets stuck before dinner I'll do a quick revert later.

**Pull request merged**
