### PR TITLE
Update afl-fuzz-redqueen.c

### PR DESCRIPTION
**Pull request by sbamohabbatchafjiri**
Hi There,

This is my solution to swap memory with a Feistel Network, and I want to examine it on Fuzzbench to see the result of code coverage if it is possible.

Regards,
Sadegh

### CODE REVIEW

**Comment by vanhauser-thc** [comment]
we do not accept PRs to stable, you must put them to the dev branch as it is mentioned in the CONTRIBUTIONS.md

I could do that for you however:
  * you do not need this to be merged to AFL++. If you want to test it on fuzzbench, you can request a test there with your own AFL++ fork with your changes
  * I do not see how your change could have any benefit and due to the overhead it will just be a bit slower.

**Comment by sbamohabbatchafjiri** [comment]
I achieved slightly better coverage on 3 targets of MAGMA with better item geometry. I believe there is a trade-off between overhead and the capability of fuzzer to generate high-quality inputs. If the code were able to generate more complex inputs, it could save time and compensate for the overhead issue, in my opinion. Moreover, the order of time complexity is O(n), which is not significant enough to have a negative impact, I think but I will be happy to have experts' feedback. Additionally, adapting the cryptographic module is in its early stages. Others may wish to apply the idea more smartly in AFL++ by replacing fully Havoc, splicing and etc. 

I requested a test here: https://github.com/google/fuzzbench/pull/1953/commits/6ce93e92102b40bfbc69427e207cfc94cbbcdf8f
but can you please let me know how to let Fuzzbench know or submit my own AFL++ fork with my changes in their experiment environment? It is first time, I am doing this and I could not find how to do.

**Comment by vanhauser-thc** [comment]
What you do is that the character replacement mechanism for the cmplog colorization part is using a different RNG.
That cannot have a noteable impact. you could use libc's rand() instead of our strong RNG, or a counter instead of an RNG, and the results would still be very close.
What you did see is rather normal fluctuations.
But maybe I just don't see it.

So if you are convinced that this is helpful - request a fuzzbench comparison run.

look at the PRs of fuzzbench there you can see how this needs to be done. for you, copying the aflplusplus directory, putting your github repo and commit id in builder.Dockerfile and that is it.

**Comment by sbamohabbatchafjiri** [comment]
Would you like to see the results on libpng, libsndfile, libtiff, Sqlite, and xmllint? I found two unique crashes and multiple unique hangs on libtiff. I am very new to working with Github, and I need a senior Githubber to help me examine my path on Fuzzbench. I have a milestone ahead in my PhD, and Github is a little complex for me as I am struggling with many other tasks that I cannot share here with you. I think there should be a more straightforward way to request help quickly. Some people are talented in certain aspects of coding and brainstorming in solution but not necessarily all aspects are easy for them, which can prevent effective collaboration with the community. So, I need a senior Githubber to help me navigate this complex environment as I am very new and have many tasks to complete. I understand that you may also be very busy, but I need someone to give me more confidence to be a part of the community at least at this stage.

IMG_0947

**Comment by sbamohabbatchafjiri** [comment]
Also, it shows that the overall edge coverage slightly improved over 5 repeats on VMs, but I am not sure if the crashes I discovered indicate new CVEs or not. Can you please help me involve testing, as both Fuzzbench and AFL++ are Google open-source products, and you may be familiar with the team as well?

Many thanks in advance.

**Comment by sbamohabbatchafjiri** [comment]
It shows this error. This branch has conflicts that must be resolved
Only those with [write access](https://docs.github.com/articles/what-are-the-different-access-permissions) to this repository can merge pull requests.
Conflicting files
nyx_mode/QEMU-Nyx
nyx_mode/QEMU_NYX_VERSION

In src/afl-forkserver.c, I clicked on "resolve conflict," but it did not progress.

**Comment by vanhauser-thc** [comment]
your code does not even compile:
```
src/afl-fuzz-redqueen.c:65:15: note: passing argument to parameter 'input' here
   65 | u8 feistel(u8 input, uint8_t key) {
      |               ^
src/afl-fuzz-redqueen.c:229:8: warning: unused variable 'm' [-Wunused-variable]
  229 |     u8 m;
      |        ^
src/afl-fuzz-redqueen.c:257:40: error: array subscript is not an integer
  257 |           c = 'A' + rand_below(aes_sbox[afl], 1 + 'F' - 'A');
      |                                        ^~~~
src/afl-fuzz-redqueen.c:269:40: error: array subscript is not an integer
  269 |           c = '2' + rand_below(aes_sbox[afl], 1 + '9' - '2');
      |                                        ^~~~
src/afl-fuzz-redqueen.c:275:40: error: array subscript is not an integer
  275 |           c = 'g' + rand_below(aes_sbox[afl], 1 + 'z' - 'g');
      |                                        ^~~~
src/afl-fuzz-redqueen.c:281:40: error: array subscript is not an integer
  281 |           c = ',' + rand_below(aes_sbox[afl], 1 + '.' - ',');
      |                                        ^~~~
src/afl-fuzz-redqueen.c:287:40: error: array subscript is not an integer
  287 |           c = '[' + rand_below(aes_sbox[afl], 1 + '`' - '[');
      |                                        ^~~~
1 warning and 10 errors generated.
make: *** [GNUmakefile:468: afl-fuzz] Error 1
```

**Comment by sbamohabbatchafjiri** [comment]
I replaced `c = feistel(afl, ((rand_below(afl, 256)) & 0xff));` with `feistel(buf[i], ((rand_below(afl, 256)) & 0xff));` as I believe the error was caused by this issue. Please let me know if the error persists. Step by step, I am learning what I should do. Also, I did not encounter an error on my system. How is it possible for code to work on my system then? Thanks.
 Is it possible for code to behave differently on different systems or factors that can influence this, including differences in compilers, compiler settings, operating systems, hardware, and dependencies?

**Comment by vanhauser-thc** [comment]
It still does not compile. and looking at the code it is obvious it cannot.

**Comment by sbamohabbatchafjiri** [comment]
Hello, could you please clarify whether you're referring to the second code in the provided link [afl-fuzz-one.c](https://github.com/AFLplusplus/AFLplusplus/pull/1976/commits/82239269c380291ef7293332a5c7613583a115fb), or the previous one ((i.e Update afl-fuzz-redqueen.c)) after the update? As I added one more code and it may cause the problem. If the previous issue with the first code has been resolved, I can proceed to address the second one accordingly in a similar way. However, if the error persists in the first code (i.e Update afl-fuzz-redqueen.c), do you have any insights on what might be causing it? My goal is to replace each 8 bits with a value from the look-up table, similar to the functionality of rand_below(afl, 256). I appreciate any guidance or advice you can offer on this matter. Thank you for your assistance!

**Comment by sbamohabbatchafjiri** [comment]
How many times a person allowed to correct the code? How can I send unique crashes I found by AFL++ and my patch on Libpng. Are unique hans are valuable? Is anyone interested in seeing unique bugs?

**Comment by vanhauser-thc** [comment]
I compiled you current code state from your patch-1 branch in your repository.
you can update as many times as you want.
but - as your code cannot compile, and for someone who can code C this is absolutely obvious,  I highly doubt your code ever worked. so whatever you tested - you must have tested something else, likely a different version of afl-fuzz or something.

**Comment by sbamohabbatchafjiri** [comment]
I ran a Kali Linux on VMware. Then fuzzed libpng as listed below:

Stage 1: 
sudo apt-get update
sudo apt-get install -y build-essential python3-dev automake git flex bison libglib2.0-dev libpixman-1-dev python3-setuptools
sudo apt-get install -y lld-11 llvm-11 llvm-11-dev clang-11 || sudo apt-get install -y lld llvm llvm-dev clang 
sudo apt-get install -y gcc-$(gcc --version|head -n1|sed 's/.* //'|sed 's/\..*//')-plugin-dev libstdc++-$(gcc --version|head -n1|sed 's/.* //'|sed 's/\..*//')-dev

Stage 2:
cd $HOME
git clone https://github.com/AFLplusplus/AFLplusplus && cd AFLplusplus
export LLVM_CONFIG="llvm-config-11"
make distrib
sudo make install

Stage 3: replacement of the original src (/home/kali/AFLplusplus/src/) with src folder (patch version) uploaded in the below link: 
https://www.dropbox.com/scl/fo/g5n929w3f3irfwfct2tgb/h?rlkey=ei45q6w9o4xgv1g0fcw44b4qm&dl=0


Stage 4: download corpus and move them in home/kali/corpus: 

https://www.dropbox.com/scl/fo/by822xzmf770mkhe4cbjq/h?rlkey=3ta3hx8nijlqyznpufxo20irh&dl=0

Stage 5: Fuzzing libpng

git clone --no-checkout https://gitlab.com/libtiff/libtiff.git

cd ~/libtiff

git checkout c145a6c14978f73bb484c955eb9f84203efcb12e

./autogen.sh

./configure
make
sudo make install


------------------------------------------

Checking out if it is installed well? 

/home/kali/libtiff/tools/tiffinfo -D -j -c -r -s -w /home/kali/libtiff/test/images/miniswhite-1c-1b.tiff                                               
TIFF Directory at offset 0x3028 (bd4)
  Image Width: 157 Image Length: 151
  Bits/Sample: 1
  Sample Format: unsigned integer
  Compression Scheme: None
  Photometric Interpretation: min-is-white
  Samples/Pixel: 1
  Rows/Strip: 409
  Planar Configuration: single image plane
  Page Number: 0-1
  DocumentName: miniswhite-1c-1b.tiff
  Software: GraphicsMagick 1.2 unreleased Q16 http://www.GraphicsMagick.org/
  1 Strips:
      0: [       8,     3020]


------------------------------------------                                                                      

ls /usr/local/bin/ | grep tiff
ls /usr/bin/ | grep tiff

tiffcp
tiffdump
tiffinfo
tiffset
tiffsplit


make clean


cd tools     
                                                                             
ls
CMakeLists.txt  Makefile.in  tiffinfo.c   tif_tools_versioninfo.rc
Makefile        tiffcp.c     tiffset.c    unsupported
Makefile.am     tiffdump.c   tiffsplit.c



cd ..                              
                                                                             
ls
aclocal.m4      config.log              libtiff-4.pc     README.md
archive         config.status           libtiff-4.pc.in  RELEASE-DATE
autogen.sh      configure               libtool          test
autom4te.cache  configure.ac            LICENSE.md       tiff.spec
build           contrib                 m4               TODO
ChangeLog       CONTRIBUTING.md         Makefile         tools
cmake           doc                     Makefile.am      VERSION
CMakeLists.txt  HOWTO-RELEASE           Makefile.in
COMMITTERS      HOWTO-SECURITY-RELEASE  placeholder.h
config          libtiff                 port
                                                                             
export LLVM_CONFIG="llvm-config-11"
CC=afl-clang-lto ./configure --prefix="/home/kali/libtiff/tools" --disable-shared            
AFL_USE_ASAN=1 make -j4    
AFL_USE_ASAN=1 make install


afl-fuzz -m none -i /home/kali/corpous/libtiff/ -o /home/kali/out/ -s 123 -- /home/kali/libtiff/tools/tiffinfo -D -j -c -r -s -w @@


Here is unique crashes and hangs I discovered:

https://www.dropbox.com/scl/fo/prad5v2107pox9om89v5u/h?rlkey=pl0q5y17zgd3j67elyz0nx5xo&dl=0

Could you please run the code on your Kali Linux in VMware and let me know if it works there?
I want to know what's wrong with code.

**Comment by vanhauser-thc** [comment]
also the code in the dropbox cannot compile. you have the same coding error there.
so afl-fuzz is never correctly built, something that the make would show you.
so likely what happens is that a previously installed afl-fuzz is being used.

**Comment by sbamohabbatchafjiri** [comment]
I am truly confused and deeply sorry to take up your time. I am sure I installed the new afl++ in December 2023 or later, but I am not exactly sure when. I wish I could send you the entire image of my Kali and AFL++ for validation, but I think it would take too much time over the internet. Anyway, I'll do my best to fix it and be back.

Thanks for your time.

**Pull request closed without merging**
