### PR TITLE
rename active_paths

### PR DESCRIPTION
**Pull request by yuawn**
Rename `active_paths` to `active_items` for better readability.

### CODE REVIEW

**Comment by yuawn** [comment]
`xxhash.h` still cannot pass code-format after code-format.
It is broken after twice code-format.

**Comment by vanhauser-thc** [comment]
yes I am aware of the issue. just restore xxhash.h (eg. copy from our afl++ repo)

**Comment by yuawn** [comment]
I resolved it in this way https://github.com/AFLplusplus/AFLplusplus/pull/1205/commits/602eafc223d76987e447b431fc75903147a40c38. It can now pass twice code format.
What do you think?

**Comment by vanhauser-thc** [comment]
if it still works as before I am fine with it! :)

**Pull request merged**
