### PR TITLE
fix if A == B always evalutes to true

### PR DESCRIPTION
**Pull request by joeyjiaojg**

### CODE REVIEW

**Comment by joeyjiaojg** [comment]
Marco cannot be compared to enum in C as it always true.

**Comment by vanhauser-thc** [comment]
I do not understand this.
`#if GUM_NATIVE_CPU == GUM_CPU_AMD64` why would this be always true?

**Comment by joeyjiaojg** [comment]
Here's the explanation https://stackoverflow.com/questions/34677148/why-does-the-c-preprocessor-consider-enum-values-as-equal

**Comment by vanhauser-thc** [comment]
ah ok, I understand now, thanks :)
I think the ifdef is wrong though, it should be `__x86_64__`

**Comment by joeyjiaojg** [comment]
Fixed

**Comment by vanhauser-thc** [comment]
thank you!

**Pull request merged**
