### PR TITLE
Allow Large Extras

### PR DESCRIPTION
**Pull request by domenukk**
This PR allows large extras, making fuzzing with huge dictionaries possible (for people that want to)...

### CODE REVIEW

**Comment by vanhauser-thc** [comment]
Is that all that is needed? Was the extras duct already growing as big as required besides the fatal?

**Comment by vanhauser-thc** [comment]
(Not at Home or Laptop to check myself)

**Comment by domenukk** [comment]
Yes it's dynamically allocated. 
However if extras get larger than the max testcase size we'll run into further problems, but that's not a large issue

**Comment by vanhauser-thc** [comment]
@domenukk max testcase size being MAX_FILE = 1MB by default? good to know but I do not think this is likely to happen.
all dictionaries we have in afl++ are ~100kb altogether :)

LGTM - IMHO you can merge

**Comment by antonio-morales** [comment]
@vanhauser-thc 1MB is more than enough xddd

**Pull request merged**
