### PR TITLE
Fix big-little support on Linux

### PR DESCRIPTION
**Pull request by WorksButNotTested**

### CODE REVIEW

**Comment by vanhauser-thc** [comment]
can you please explain?

**Comment by WorksButNotTested** [comment]
> can you please explain?

Does the comment in the PR suffice?

**Comment by vanhauser-thc** [comment]
would I ask if that would be the case?
the PR is wrong to me, but I do not know what you try to achieve.

**Comment by WorksButNotTested** [comment]
> would I ask if that would be the case?
> the PR is wrong to me, but I do not know what you try to achieve.

Sorry. Didn’t know if you’d seen it. I’m hoping that in the event you run a single instance of afl++ it will be bound to one of the big cores rather than a little core. As that is likely what the user would want?

**Comment by vanhauser-thc** [comment]
replaced with 7bd2899

**Pull request closed without merging**
