### PR TITLE
Update QEMUAFL_VERSION

### PR DESCRIPTION
**Pull request by nickswang**
https://github.com/nyx-fuzz/QEMU-Nyx/commit/1def26f83e83556d767754581fa52081ffb54b09

You need this commit or it dies when running not in intel-pt mode

### CODE REVIEW

**Comment by nickswang** [comment]
@vanhauser-thc I noted this change is present in your PR but it seems like yours is blocked at present - this will fix nyx_mode in the meantime

**Comment by SonicStark** [comment]
Don't do that, plz. Actually all changes will be merged into `dev` FIRST, and THEN synced to `stable`.

See：
 - [#branches (README.md)](https://github.com/AFLplusplus/AFLplusplus?tab=readme-ov-file#branches)
 - [CONTRIBUTING.md](https://github.com/AFLplusplus/AFLplusplus/blob/stable/CONTRIBUTING.md)

**Comment by vanhauser-thc** [comment]
if you need the current qemuafl state just use the dev branch.
this week dev will be merged into stable.

**Comment by vanhauser-thc** [comment]
also you updated the wrong file. you updated qemuafl which has nothing to do with qemu-nyx

**Comment by nickswang** [comment]
haha, whoops. that's what I get for doing it at the end of the day. Thanks for fixing it, I just wanted to help anyone else who didn't know why their nyx wasn't working all of a sudden.

**Pull request closed without merging**
