### PR TITLE
Better solution for aarch 64 is to consider literral unsigned long long

### PR DESCRIPTION
**Pull request by devnexen**

### CODE REVIEW

**Comment by devnexen** [comment]
I reset locally from previous commit.

**Comment by vanhauser-thc** [comment]
still breaks:
```cc -O3 -funroll-loops -march=native -D_FORTIFY_SOURCE=2 -Wall -g -Wno-pointer-sign -I include/ -Werror -DAFL_PATH=\"/usr/local/lib/afl\" -DBIN_PATH=\"/usr/local/bin\" -DDOC_PATH=\"/usr/local/share/doc/afl\" -flto=full -c src/afl-common.c -o src/afl-common.o

src/afl-common.c: In function ‘stringify_int’:

src/afl-common.c:458:24: error: format ‘%lu’ expects argument of type ‘long unsigned int’, but argument 4 has type ‘long long unsigned int’ [-Werror=format=]

src/afl-common.c:450:32:

       snprintf(buf, len, _fmt, ((_cast)val) / (_divisor)); \
```
just work via travis to fix this :)

**Comment by vanhauser-thc** [comment]
https://travis-ci.com/github/AFLplusplus/AFLplusplus/jobs/318577612

**Comment by devnexen** [comment]
But do not know if on Travis the previous commit was reset ?

**Comment by vanhauser-thc** [comment]
the reset is only for you locally, its not in the commit/PR

**Pull request closed without merging**
