### PR TITLE
llvm instrumentation trying to delete all static data

### PR DESCRIPTION
**Pull request by devnexen**
at module end of pass with llvm_shutdown and is concurrent safe.

### CODE REVIEW

**Comment by vanhauser-thc** [comment]
thank you.
what does that do?

**Comment by devnexen** [comment]
it deletes all static data created by static calls like `BasicBlock::Create`. the llvm_shutdown_obj just calls `llvm::llvm_shutdown` on destruction.

**Comment by vanhauser-thc** [comment]
I still have no clue what this changes in the compiled code ... well lets see ...

**Comment by vanhauser-thc** [comment]
it crashes clang 14 when compiling with laf or cmplog, had to revert it :-(

**Comment by vanhauser-thc** [comment]
this is the backtrace:
```
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace, preprocessed source, and associated run script.
Stack dump:
0.	Program arguments: /usr/lib/llvm-14/bin/clang -cc1 -triple x86_64-pc-linux-gnu -emit-obj --mrelax-relocations -disable-free -clear-ast-before-backend -disable-llvm-verifier -discard-value-names -main-file-name test-uint_cases.c -mrelocation-model pic -pic-level 2 -pic-is-pie -mframe-pointer=none -fmath-errno -ffp-contract=on -fno-rounding-math -mconstructor-aliases -funwind-tables=2 -target-cpu x86-64 -tune-cpu generic -mllvm -treat-scalable-fixed-error-as-warning -debug-info-kind=constructor -dwarf-version=5 -debugger-tuning=gdb -fcoverage-compilation-dir=/prg/dev/test -resource-dir /usr/lib/llvm-14/lib/clang/14.0.6 -D "INT_TYPE=long long" -D __AFL_HAVE_MANUAL_CONTROL=1 -D __AFL_COMPILER=1 -D FUZZING_BUILD_MODE_UNSAFE_FOR_PRODUCTION=1 -D "__AFL_FUZZ_INIT()=int __afl_sharedmem_fuzzing = 1;extern unsigned int *__afl_fuzz_len;extern unsigned char *__afl_fuzz_ptr;unsigned char __afl_fuzz_alt[1048576];unsigned char *__afl_fuzz_alt_ptr = __afl_fuzz_alt;" -D "__AFL_COVERAGE()=int __afl_selective_coverage = 1;void __afl_coverage_discard();void __afl_coverage_skip();void __afl_coverage_on();void __afl_coverage_off();" -D "__AFL_COVERAGE_START_OFF()=int __afl_selective_coverage_start_off = 1;" -D __AFL_COVERAGE_ON()=__afl_coverage_on() -D __AFL_COVERAGE_OFF()=__afl_coverage_off() -D __AFL_COVERAGE_DISCARD()=__afl_coverage_discard() -D __AFL_COVERAGE_SKIP()=__afl_coverage_skip() -D "__AFL_FUZZ_TESTCASE_BUF=(__afl_fuzz_ptr ? __afl_fuzz_ptr : __afl_fuzz_alt_ptr)" -D "__AFL_FUZZ_TESTCASE_LEN=(__afl_fuzz_ptr ? *__afl_fuzz_len : (*__afl_fuzz_len = read(0, __afl_fuzz_alt_ptr, 1048576)) == 0xffffffff ? 0 : *__afl_fuzz_len)" -D "__AFL_LOOP(_A)=({ static volatile char *_B __attribute__((used,unused));  _B = (char*)\"##SIG_AFL_PERSISTENT##\"; extern int __afl_connected;__attribute__((visibility(\"default\"))) int _L(unsigned int) __asm__(\"__afl_persistent_loop\"); _L(__afl_connected ? _A : 1); })" -D "__AFL_INIT()=do { static volatile char *_A __attribute__((used,unused));  _A = (char*)\"##SIG_AFL_DEFER_FORKSRV##\"; __attribute__((visibility(\"default\"))) void _I(void) __asm__(\"__afl_manual_init\"); _I(); } while (0)" -internal-isystem /usr/lib/llvm-14/lib/clang/14.0.6/include -internal-isystem /usr/local/include -internal-isystem /usr/lib/gcc/x86_64-linux-gnu/12/../../../../x86_64-linux-gnu/include -internal-externc-isystem /usr/include/x86_64-linux-gnu -internal-externc-isystem /include -internal-externc-isystem /usr/include -O3 -Wno-unused-command-line-argument -Wno-unused-command-line-argument -fdebug-compilation-dir=/prg/dev/test -ferror-limit 19 -funroll-loops -fgnuc-version=4.2.1 -fno-legacy-pass-manager -vectorize-loops -vectorize-slp -fpass-plugin=/prg/dev/test/../split-compares-pass.so -fpass-plugin=/prg/dev/test/../afl-llvm-pass.so -faddrsig -D__GCC_HAVE_DWARF2_CFI_ASM=1 -o /tmp/test-uint_cases-f7b82d.o -x c ./test-uint_cases.c
1.	<eof> parser at end of file
 #0 0x00007fffeeaa5291 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/lib/x86_64-linux-gnu/libLLVM-14.so.1+0xea5291)
 #1 0x00007fffeeaa2fbe llvm::sys::RunSignalHandlers() (/lib/x86_64-linux-gnu/libLLVM-14.so.1+0xea2fbe)
 #2 0x00007fffeeaa57c6 (/lib/x86_64-linux-gnu/libLLVM-14.so.1+0xea57c6)
 #3 0x00007fffeda5af90 (/lib/x86_64-linux-gnu/libc.so.6+0x3bf90)
 #4 0x00007fffeebe445d llvm::PMTopLevelManager::addImmutablePass(llvm::ImmutablePass*) (/lib/x86_64-linux-gnu/libLLVM-14.so.1+0xfe445d)
 #5 0x00007fffeebe36ff llvm::PMTopLevelManager::schedulePass(llvm::Pass*) (/lib/x86_64-linux-gnu/libLLVM-14.so.1+0xfe36ff)
 #6 0x00007ffff5e89525 clang::EmitBackendOutput(clang::DiagnosticsEngine&, clang::HeaderSearchOptions const&, clang::CodeGenOptions const&, clang::TargetOptions const&, clang::LangOptions const&, llvm::StringRef, llvm::Module*, clang::BackendAction, std::unique_ptr<llvm::raw_pwrite_stream, std::default_delete<llvm::raw_pwrite_stream> >) (/lib/x86_64-linux-gnu/libclang-cpp.so.14+0x1889525)
 #7 0x00007ffff61adf95 (/lib/x86_64-linux-gnu/libclang-cpp.so.14+0x1badf95)
 #8 0x00007ffff5034914 clang::ParseAST(clang::Sema&, bool, bool) (/lib/x86_64-linux-gnu/libclang-cpp.so.14+0xa34914)
 #9 0x00007ffff61aa261 clang::CodeGenAction::ExecuteAction() (/lib/x86_64-linux-gnu/libclang-cpp.so.14+0x1baa261)
#10 0x00007ffff6b4bb87 clang::FrontendAction::Execute() (/lib/x86_64-linux-gnu/libclang-cpp.so.14+0x254bb87)
#11 0x00007ffff6aa14f6 clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) (/lib/x86_64-linux-gnu/libclang-cpp.so.14+0x24a14f6)
#12 0x00007ffff6bc593b clang::ExecuteCompilerInvocation(clang::CompilerInstance*) (/lib/x86_64-linux-gnu/libclang-cpp.so.14+0x25c593b)
#13 0x0000000000413e93 cc1_main(llvm::ArrayRef<char const*>, char const*, void*) (/usr/lib/llvm-14/bin/clang+0x413e93)
#14 0x00000000004120cc (/usr/lib/llvm-14/bin/clang+0x4120cc)
#15 0x0000000000411f17 main (/usr/lib/llvm-14/bin/clang+0x411f17)
#16 0x00007fffeda4618a __libc_start_call_main ./csu/../sysdeps/nptl/libc_start_call_main.h:74:3
#17 0x00007fffeda46245 call_init ./csu/../csu/libc-start.c:128:20
#18 0x00007fffeda46245 __libc_start_main ./csu/../csu/libc-start.c:368:5
#19 0x000000000040efb1 _start (/usr/lib/llvm-14/bin/clang+0x40efb1)
clang: error: unable to execute command: Segmentation fault
clang: error: clang frontend command failed due to signal (use -v to see invocation)
Debian clang version 14.0.6
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/lib/llvm-14/bin
clang: note: diagnostic msg: 
********************

PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
clang: note: diagnostic msg: /tmp/test-uint_cases-e3d29d.c
clang: note: diagnostic msg: /tmp/test-uint_cases-e3d29d.sh
clang: note: diagnostic msg: 

********************
```

**Comment by devnexen** [comment]
ah sorry for that.

**Pull request merged**
