### PR TITLE
OpenBSD build fix proposal.

### PR DESCRIPTION
**Pull request by devnexen**
Mainly the gcc plugin, using one of the egcc/eg++ version available.
Needs pthread flag to r/w lock api.

### CODE REVIEW

**Comment by vanhauser-thc** [comment]
LGTM :)
@devnexen @domenukk  do you know why unicornafl changes show up in in the PR?

**Comment by andreafioraldi** [comment]
@devnexen I just noticed that you never added yourself to the special thanks section in the readme! https://github.com/AFLplusplus/AFLplusplus#special-thanks

**Comment by devnexen** [comment]
@vanhauser-thc  no idea :-)

@andreafioaraldi Ah right I tought like php repo it was main maintainers filling this kind of infos.

**Comment by domenukk** [comment]
I'll just merge and make sure unicorn is Allright afterwards

**Pull request merged**
