### PR TITLE
Docs content - quality assurance

### PR DESCRIPTION
**Pull request by llzmb**

### CODE REVIEW

**Comment by vanhauser-thc** [comment]
looks great so far!

**Comment by llzmb** [comment]
Quick question: Is "never zero" still a thing? We deleted the README.neverzero.md and I cannot find anything in the docs.

> AFL++ performs "never zero" counting in its bitmap. You can read more about this
> here:
> * [instrumentation/README.neverzero.md](../instrumentation/README.neverzero.md)

Source: https://github.com/AFLplusplus/AFLplusplus/blob/3506077fd6f250f3c080b58ea3bae117c3b122da/docs/fuzzing_in_depth.md?plain=1#L159-L161

**Comment by vanhauser-thc** [comment]
yes it is the default for most instrumentations. there are environment variables to disable it. 
Maybe it should be preserved... just add the original document as an extra content to README.llvm.md

**Comment by llzmb** [comment]
It's a wrap! :)

**Pull request merged**
