### PR TITLE
 Get-set-fuzz

### PR DESCRIPTION
**Pull request by sunle-af**
It's a very easy tutorial on how to get started with fuzzing.
it uses binary as fuzzgoat.
The issue that I faced while getting to fuzzing is there were no readable or articles available.

### CODE REVIEW

**Comment by vanhauser-thc** [comment]
IMHO this is too simple - and then even does not explain anything.
except people copy-pasting this, they do not learn something.
(and unnecessary steps like creating the out directory)

Also we rather link to guides than include them, there is a specific section for this in the main README.

so if you expand on the guide, they why and how etc. and make it available somewhere we can put a pointer in the README and the aflplus.plus website.

**Comment by sunle-af** [comment]
Okay Sir thanks for the clarification.
if you can reply to this mail It would be great Sir,I really want to work
with afl++ and contribute to the repository  but I am new and I am not
understanding where to start,I am trying to do this last 2 months and the
only idea that i came up with was this guide.If you can say me what can I
do and where to literally start with this whole repository. I hope you
understand.I am trying to work on this but it didn't help me in any way.If
you can say anything that would be great.

**Comment by vanhauser-thc** [comment]
you could start by following the other guides that are linked in the README, that will help you learning and understanding.
also the README.md is being completely rewritten so on Tuesday this will also help you.

**Comment by sunle-af** [comment]
Hello sir,
I had a question regarding this organisation will it be taking any part in
upcoming Google summer of code.(gsoc21)

**Comment by vanhauser-thc** [comment]
Maybe.
We have two student in this year's GSOC which was our first. Both perform really well and we are so far happy with the results and the event.
If we take part next year will depend if we have topics that fit the skill and time for a GSOC stundent - or a student proposes something that we find interesting.

**Comment by sunle-af** [comment]
Thanks sir,
I look forward to contributing to your repository

**Pull request closed without merging**
