### PR TITLE
LLVM cmplog factoring custom Instruction iterator with added restriction

### PR DESCRIPTION
**Pull request by devnexen**

### CODE REVIEW

**Comment by vanhauser-thc** [comment]
Thanks!

**Comment by vanhauser-thc** [comment]
this PR killed cmplog compilation on fuzzbench where they use `clang version 15.0.0 (https://github.com/llvm/llvm-project.git bf7f8d6fa6f460bf0a16ffec319cd71592216bf4)`.
this also impacts oss-fuzz, so we cannot update afl++ there.

I can revert this PR, but maybe you know an easy way to fix it?

**Comment by vanhauser-thc** [comment]
@devnexen fyi I reverted the PR so ppl using dev can compile cmplog with llvm 15

**Comment by devnexen** [comment]
ah ok np understood :-)

**Pull request merged**
