### PR TITLE
Fix build failures with clang 15

### PR DESCRIPTION
**Pull request by glandium**

### CODE REVIEW

**Comment by vanhauser-thc** [comment]
thank you.
what is that about opaque pointers? what are we missing?

and maybe you can help because the llvm community support is atrocious ... our LTO plugin is not loading in lld for 3 weeks now due some change. I tried the new options to load a pass and also the debug option (-Wl,--lto-debug-pass-manager -Wl,--load-pass-plugin=%s/SanitizerCoverageLTO.so) but it shows zero debug messages about it and its not loaded and executed ...)

**Comment by glandium** [comment]
> what is that about opaque pointers? what are we missing?

I haven't looked in depth. See the comment in the patch for the assertion crash that happens when building without disabling opaque pointers.

> our LTO plugin is not loading in lld

Sorry, I can't help you here.

**Comment by vanhauser-thc** [comment]
so the opaque pointer thing is a temporary work around?

**Comment by glandium** [comment]
Until someone figures out what's needed in afl++.

**Comment by vanhauser-thc** [comment]
> Until someone figures out what's needed in afl++.

ah you mean there is a change in llvm15 that is not a bug in llvm but needs a change in afl++? then this needs a fix in afl++, not a workaround in afl-cc ... do you have an example C/C++ source that triggers this?

**Comment by glandium** [comment]
It happens during the build of afl++ itself.

**Comment by devnexen** [comment]
llvm committer here. note that llvm 15 will have a release this next autumn (if all goes well), depends from where you got your version up to a certain git commit as I could not reproduce your issue with the actual github repo state.

**Comment by glandium** [comment]
It was happening on e82e4fa7ef71. The full stack trace looks like:
```
clang-15: /builds/worker/fetches/clang/include/llvm/IR/Type.h:385: llvm::Type *llvm::Type::getNonOpaquePointerElementType() const: Assertion `NumContainedTys && "Attempting to get element type of opaque pointer"' failed.
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace, preprocessed source, and associated run script.
Stack dump:
0.	Program arguments: /builds/worker/fetches/clang/bin/clang-15 -cc1 -triple x86_64-unknown-linux-gnu -emit-obj --mrelax-relocations -disable-free -clear-ast-before-backend -disable-llvm-verifier -discard-value-names -main-file-name test-instr.c -mrelocation-model pic -pic-level 2 -fhalf-no-semantic-interposition -mframe-pointer=none -fmath-errno -ffp-contract=on -fno-rounding-math -mconstructor-aliases -funwind-tables=2 -target-cpu x86-64 -tune-cpu generic -mllvm -treat-scalable-fixed-error-as-warning -debug-info-kind=constructor -dwarf-version=5 -debugger-tuning=gdb -fcoverage-compilation-dir=/builds/worker/fetches/AFLplusplus -resource-dir /builds/worker/fetches/clang/lib/clang/15.0.0 -D _FORTIFY_SOURCE=2 -I ./include/ -I ./instrumentation/ -D AFL_PATH=\"//lib/afl\" -D BIN_PATH=\"//bin\" -D LLVM_BINDIR=\"/builds/worker/fetches/clang/bin\" -D VERSION=\"++4.01a\" -D LLVM_LIBDIR=\"/builds/worker/fetches/clang/lib\" -D LLVM_VERSION=\"15.0.0\" -D AFL_CLANG_FLTO=\"-flto=full\" -D AFL_REAL_LD=\"/builds/worker/fetches/clang/bin/ld.lld\" -D AFL_CLANG_LDPATH=\"1\" -D AFL_CLANG_FUSELD=\"1\" -D CLANG_BIN=\"/builds/worker/fetches/clang/bin/clang\" -D CLANGPP_BIN=\"/builds/worker/fetches/clang/bin/clang++\" -D USE_BINDIR=1 -D __AFL_HAVE_MANUAL_CONTROL=1 -D __AFL_COMPILER=1 -D FUZZING_BUILD_MODE_UNSAFE_FOR_PRODUCTION=1 -D "__AFL_FUZZ_INIT()=int __afl_sharedmem_fuzzing = 1;extern unsigned int *__afl_fuzz_len;extern unsigned char *__afl_fuzz_ptr;unsigned char __afl_fuzz_alt[1048576];unsigned char *__afl_fuzz_alt_ptr = __afl_fuzz_alt;" -D "__AFL_COVERAGE()=int __afl_selective_coverage = 1;void __afl_coverage_discard();void __afl_coverage_skip();void __afl_coverage_on();void __afl_coverage_off();" -D "__AFL_COVERAGE_START_OFF()=int __afl_selective_coverage_start_off = 1;" -D __AFL_COVERAGE_ON()=__afl_coverage_on() -D __AFL_COVERAGE_OFF()=__afl_coverage_off() -D __AFL_COVERAGE_DISCARD()=__afl_coverage_discard() -D __AFL_COVERAGE_SKIP()=__afl_coverage_skip() -D "__AFL_FUZZ_TESTCASE_BUF=(__afl_fuzz_ptr ? __afl_fuzz_ptr : __afl_fuzz_alt_ptr)" -D "__AFL_FUZZ_TESTCASE_LEN=(__afl_fuzz_ptr ? *__afl_fuzz_len : (*__afl_fuzz_len = read(0, __afl_fuzz_alt_ptr, 1048576)) == 0xffffffff ? 0 : *__afl_fuzz_len)" -D "__AFL_LOOP(_A)=({ static volatile char *_B __attribute__((used,unused));  _B = (char*)\"##SIG_AFL_PERSISTENT##\"; __attribute__((visibility(\"default\"))) int _L(unsigned int) __asm__(\"__afl_persistent_loop\"); _L(_A); })" -D "__AFL_INIT()=do { static volatile char *_A __attribute__((used,unused));  _A = (char*)\"##SIG_AFL_DEFER_FORKSRV##\"; __attribute__((visibility(\"default\"))) void _I(void) __asm__(\"__afl_manual_init\"); _I(); } while (0)" -internal-isystem /builds/worker/fetches/clang/lib/clang/15.0.0/include -internal-isystem /usr/local/include -internal-isystem /usr/lib/gcc/x86_64-linux-gnu/10/../../../../x86_64-linux-gnu/include -internal-externc-isystem /usr/include/x86_64-linux-gnu -internal-externc-isystem /include -internal-externc-isystem /usr/include -O3 -Wno-unused-command-line-argument -Wall -Wno-cast-qual -Wno-variadic-macros -Wno-pointer-sign -Wno-deprecated -Wno-unused-function -Wno-unused-command-line-argument -fdebug-compilation-dir=/builds/worker/fetches/AFLplusplus -fdebug-prefix-map=/builds/worker/fetches/AFLplusplus=llvm_mode -ferror-limit 19 -funroll-loops -fno-builtin-strcmp -fno-builtin-strncmp -fno-builtin-strcasecmp -fno-builtin-strncasecmp -fno-builtin-memcmp -fno-builtin-bcmp -fno-builtin-strstr -fno-builtin-strcasestr -fgnuc-version=4.2.1 -vectorize-loops -vectorize-slp -fpass-plugin=./split-switches-pass.so -fpass-plugin=./compare-transform-pass.so -fpass-plugin=./split-compares-pass.so -fpass-plugin=./SanitizerCoveragePCGUARD.so -faddrsig -D__GCC_HAVE_DWARF2_CFI_ASM=1 -o /tmp/test-instr-9a9c38.o -x c ./test-instr.c
1.	<eof> parser at end of file
2.	Optimizer
 #0 0x00007fdbc3610bf3 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/builds/worker/fetches/clang/bin/../lib/libLLVM-15git.so+0x7a6bf3)
 #1 0x00007fdbc3610efb SignalHandler(int) Signals.cpp:0:0
 #2 0x00007fdbc9a2d140 __restore_rt (/lib/x86_64-linux-gnu/libpthread.so.0+0x14140)
 #3 0x00007fdbc29b3ce1 raise (/lib/x86_64-linux-gnu/libc.so.6+0x3bce1)
 #4 0x00007fdbc299d537 abort (/lib/x86_64-linux-gnu/libc.so.6+0x25537)
 #5 0x00007fdbc299d40f (/lib/x86_64-linux-gnu/libc.so.6+0x2540f)
 #6 0x00007fdbc29ac662 (/lib/x86_64-linux-gnu/libc.so.6+0x34662)
 #7 0x00007fdbc098dcbc (anonymous namespace)::ModuleSanitizerCoverageAFL::CreateSecStartEnd(llvm::Module&, char const*, llvm::Type*) /builds/worker/fetches/AFLplusplus/instrumentation/SanitizerCoveragePCGUARD.so.cc:0:0
 #8 0x00007fdbc098d40f (anonymous namespace)::ModuleSanitizerCoverageAFL::CreateInitCallsForSections(llvm::Module&, char const*, char const*, llvm::Type*, char const*) /builds/worker/fetches/AFLplusplus/instrumentation/SanitizerCoveragePCGUARD.so.cc:341:27
 #9 0x00007fdbc098cd30 (anonymous namespace)::ModuleSanitizerCoverageAFL::instrumentModule(llvm::Module&, llvm::function_ref<llvm::DominatorTree const* (llvm::Function&)>, llvm::function_ref<llvm::PostDominatorTree const* (llvm::Function&)>) /builds/worker/fetches/AFLplusplus/instrumentation/SanitizerCoveragePCGUARD.so.cc:516:12
#10 0x00007fdbc0989df4 (anonymous namespace)::ModuleSanitizerCoverageAFL::run(llvm::Module&, llvm::AnalysisManager<llvm::Module>&) /builds/worker/fetches/AFLplusplus/instrumentation/SanitizerCoveragePCGUARD.so.cc:307:7
#11 0x00007fdbc0989df4 llvm::detail::PassModel<llvm::Module, (anonymous namespace)::ModuleSanitizerCoverageAFL, llvm::PreservedAnalyses, llvm::AnalysisManager<llvm::Module>>::run(llvm::Module&, llvm::AnalysisManager<llvm::Module>&) /builds/worker/fetches/clang/include/llvm/IR/PassManagerInternal.h:88:17
#12 0x00007fdbc49a74fd llvm::PassManager<llvm::Module, llvm::AnalysisManager<llvm::Module>>::run(llvm::Module&, llvm::AnalysisManager<llvm::Module>&) (/builds/worker/fetches/clang/bin/../lib/libLLVM-15git.so+0x1b3d4fd)
#13 0x00007fdbc8c1f5ef (anonymous namespace)::EmitAssemblyHelper::RunOptimizationPipeline(clang::BackendAction, std::unique_ptr<llvm::raw_pwrite_stream, std::default_delete<llvm::raw_pwrite_stream>>&, std::unique_ptr<llvm::ToolOutputFile, std::default_delete<llvm::ToolOutputFile>>&) BackendUtil.cpp:0:0
#14 0x00007fdbc8c1c396 clang::EmitBackendOutput(clang::DiagnosticsEngine&, clang::HeaderSearchOptions const&, clang::CodeGenOptions const&, clang::TargetOptions const&, clang::LangOptions const&, llvm::StringRef, llvm::Module*, clang::BackendAction, std::unique_ptr<llvm::raw_pwrite_stream, std::default_delete<llvm::raw_pwrite_stream>>) (/builds/worker/fetches/clang/bin/../lib/libclang-cpp.so.15git+0x231c396)
#15 0x00007fdbc893a71d clang::BackendConsumer::HandleTranslationUnit(clang::ASTContext&) crtstuff.c:0:0
#16 0x00007fdbc89e22c4 clang::ParseAST(clang::Sema&, bool, bool) (/builds/worker/fetches/clang/bin/../lib/libclang-cpp.so.15git+0x20e22c4)
#17 0x00007fdbc8e6f97d clang::FrontendAction::Execute() (/builds/worker/fetches/clang/bin/../lib/libclang-cpp.so.15git+0x256f97d)
#18 0x00007fdbc8e29802 clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) (/builds/worker/fetches/clang/bin/../lib/libclang-cpp.so.15git+0x2529802)
#19 0x00007fdbc8e8b3d3 clang::ExecuteCompilerInvocation(clang::CompilerInstance*) (/builds/worker/fetches/clang/bin/../lib/libclang-cpp.so.15git+0x258b3d3)
#20 0x0000555c3ff9ef38 cc1_main(llvm::ArrayRef<char const*>, char const*, void*) (/builds/worker/fetches/clang/bin/clang-15+0x16f38)
#21 0x0000555c3ff9da12 ExecuteCC1Tool(llvm::SmallVectorImpl<char const*>&) driver.cpp:0:0
#22 0x0000555c3ff9c510 main (/builds/worker/fetches/clang/bin/clang-15+0x14510)
#23 0x00007fdbc299ed0a __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x26d0a)
#24 0x0000555c3ff9b4cf _start (/builds/worker/fetches/clang/bin/clang-15+0x134cf)
```

**Comment by devnexen** [comment]
it s a couple of days old commit, if this is possible for you to checkout a more up to date version and try to see if this still happens ? in my side I can even pass the unit tests.

**Comment by glandium** [comment]
It's 24 hours old, actually. I tried 8b8281f35475 which was the tip 50 minutes ago, and it still reproduces.

**Comment by devnexen** [comment]
my bad I misread the date in the git history. how do you build llvm itself (I enable debug symbols and enable clang in my side) ?

**Comment by vanhauser-thc** [comment]
@glandium
hmm weird. the error report is from compiling test-instr.c ... 

I compiled llvm-15 from this state:
commit f6366ef7f4f3cf1182fd70e0c50a9fa54374b612 (HEAD -> main, origin/main, origin/HEAD)
Date:   Fri May 13 09:12:07 2022 +0200

but for me it compiles fine.

@devnexen 

```
git clone --depth=1 https://github.com/llvm/llvm-project
cd llvm-project
mkdir build
cd build
cmake \
    -DCLANG_INCLUDE_DOCS="OFF" \
    -DCMAKE_BUILD_TYPE=Release \
    -DLLVM_BINUTILS_INCDIR=/usr/include/ \
    -DLLVM_BUILD_LLVM_DYLIB="ON" \
    -DLLVM_ENABLE_BINDINGS="OFF" \
    -DLLVM_ENABLE_PROJECTS='clang;compiler-rt;libcxx;libcxxabi;libunwind;lld' \
    -DLLVM_ENABLE_WARNINGS="OFF" \
    -DLLVM_INCLUDE_BENCHMARKS="OFF" \
    -DLLVM_INCLUDE_DOCS="OFF" \
    -DLLVM_INCLUDE_EXAMPLES="OFF" \
    -DLLVM_INCLUDE_TESTS="OFF" \
    -DLLVM_LINK_LLVM_DYLIB="ON" \
    -DLLVM_TARGETS_TO_BUILD="host" \
    ../llvm/ && \
cmake --build . -j4
```

**Comment by vanhauser-thc** [comment]
hmm @glandium what cmake config did you do to compile your llvm? I need to reproduce this.

**Comment by glandium** [comment]
Ok, it turns out I was on an old revision of Afl++. Current tip is not crashing.

**Pull request merged**
