### PR TITLE
setting general schedule priority for performance on Mac.

### PR DESCRIPTION
**Pull request by devnexen**

### CODE REVIEW

**Comment by vanhauser-thc** [comment]
isnt user interactive more performant setting?

**Comment by devnexen** [comment]
I admit I struggled choosing between those two but felt more fit for the nature of AFL++.

**Comment by vanhauser-thc** [comment]
traditionally afl tries to grab as most resources as possible to be as fast as possible with fuzzing.
I am not a Mac user  - I guess it cannot be run with the Desktop?
in that case I would propose that if a Mac desktop is used then the current prio is set, if a Mac server is used, then the interactive user prio?

**Comment by devnexen** [comment]
oh it works even with non server edition, just tried a fuzz run with interactive setting seems ok.

**Comment by vanhauser-thc** [comment]
thank you!

**Pull request merged**
