### PR TITLE
Edit list of environment variables

### PR DESCRIPTION
**Pull request by llzmb**
Changes:
- Sort environment variables alphabetically in each topic (where appropriate).
- Remove redundant variables (AFL_NO_CPU_RED).
- Fix formatting of code in lists.
- Fix line breaks.
- Edit language here and there.

This PR is still WIP.

### CODE REVIEW

**Comment by llzmb** [comment]
Does "GNU as" mean "GNU assembler"? So, is this sentence complete?

> `AFL_AS`, since this toolchain does not directly invoke GNU as.

https://github.com/AFLplusplus/AFLplusplus/blob/9325a4fcbb8eb4ed1d71f93de5301bf1a9a68253/docs/env_variables.md?plain=1#L119

**Comment by vanhauser-thc** [comment]
> Does "GNU as" mean "GNU assembler"? So, is this sentence complete?
> 
> > `AFL_AS`, since this toolchain does not directly invoke GNU as.
> 
> https://github.com/AFLplusplus/AFLplusplus/blob/9325a4fcbb8eb4ed1d71f93de5301bf1a9a68253/docs/env_variables.md?plain=1#L119

"GNU" is an institution, "as" is a tool, the sentence is correct :) but maybe set "as" in quotes: "`as`"

**Comment by llzmb** [comment]
Is the hierarchy of the headings correct?

```
## 2) Settings for LLVM and LTO: afl-clang-fast / afl-clang-fast++ / afl-clang-lto / afl-clang-lto++
### Select the instrumentation mode
### LTO
```

LTO is an instrumentation mode, right? So maybe:

```
## 2) Settings for LLVM and LTO: afl-clang-fast / afl-clang-fast++ / afl-clang-lto / afl-clang-lto++
### Select the instrumentation mode
#### LTO
```

**Comment by llzmb** [comment]
Not sure if I get the meaning of the sentence. Can I remove "scripts" or "scripting"?

> This can help when embedding `afl-cmin` or `afl-showmap` in other scripts scripting.

https://github.com/AFLplusplus/AFLplusplus/blob/9325a4fcbb8eb4ed1d71f93de5301bf1a9a68253/docs/env_variables.md?plain=1#L577

**Comment by llzmb** [comment]
To do: QA for chapter 2 and 4.

**Comment by vanhauser-thc** [comment]
> LTO is an instrumentation mode, right? So maybe:
> 
> ```
> ## 2) Settings for LLVM and LTO: afl-clang-fast / afl-clang-fast++ / afl-clang-lto / afl-clang-lto++
> ### Select the instrumentation mode
> #### LTO
> ```

yes that one is correct

> Not sure if I get the meaning of the sentence. Can I remove "scripts" or "scripting"?
> 
> > This can help when embedding `afl-cmin` or `afl-showmap` in other scripts scripting.
> 
> https://github.com/AFLplusplus/AFLplusplus/blob/9325a4fcbb8eb4ed1d71f93de5301bf1a9a68253/docs/env_variables.md?plain=1#L577

just remove "scripting" then it is fine :)

**Pull request merged**
