### PR TITLE
Superion mutator

### PR DESCRIPTION
**Pull request by adrian-rt**
Apologies, I couldn't clean it. make clean didn't work, not sure why. I didn't want to remove stuff, to make sure I don't break it.
a README.md has been added as well.

### CODE REVIEW

**Comment by vanhauser-thc** [comment]
Hi!

as I said, as long as it is build with cmake we will not ship afl++ with it. also we would need to shepherd you to improve the code quality :)
If you do not have the time to do that - as you said - then just create a repository for this customer mutator and we will reference from it from afl++ documentation.

**Comment by adrian-rt** [comment]
Hi,

ok, I thought you wanted it here so you can improve on it.

In this case, I'll create my own repo so that you can reference it.

It's already merged in my own repo, btw, is this what you meant?
https://github.com/am06/AFLplusplus/tree/superion_mutator/custom_mutators/superion_mutator

**Comment by vanhauser-thc** [comment]
> ok, I thought you wanted it here so you can improve on it.

sure! I understood you however to have no time.
leave it here and work on it as you have the time.
step 1 is -> remove cmake and replace it with a Makefile (and a build_superion.sh if that is needed for stuff).

> In this case, I'll create my own repo so that you can reference it.
> 
> It's already merged in my own repo, btw, is this what you meant?
> https://github.com/am06/AFLplusplus/tree/superion_mutator/custom_mutators/superion_mutator

no, people should not check out your whole repository as they will miss all the improvements we will be doing in afl++ :)
just put the contents of /superion_mutator there

**Comment by adrian-rt** [comment]
ok, here it is as a new repo just for this mutator:

https://github.com/am06/superion-mutator

**Comment by vanhauser-thc** [comment]
I added the link to the main README and the README in the custom_mutator directory.
Just update this PR with the removal of cmake etc. when you have the time for it

**Comment by adrian-rt** [comment]
also, as an fyi: I changed my github username, so you might want to update the link in the README to:

https://github.com/adrian-rt/superion-mutator

It's currently redirecting just fine, but this is just an FYI to avoid any confusion. thanks.

**Comment by vanhauser-thc** [comment]
done :)

**Comment by domenukk** [comment]
Great work! :)

**Pull request closed without merging**
